Add changelog entry for FreeType version bump
alacritty/alacritty pull request #4226
Opened 2020-09-13 19:32 UTC by chrisduerr

2020-09-13 19:32 UTC, chrisduerr reviewed
This is quite relevant information for package maintainers on Linux, so it's probably a good idea to make this very clear.

2020-09-14 09:47 UTC, kchibisov commented
>This is quite relevant information for package maintainers on Linux, so it's probably a good idea to make this very clear.

The problem is that it's in 0.5.0, so the packagers should check that on 0.5.0, however the minimum version is required for source based distros(assuming a lot of version of freetype) tbqh, since in binary distros you'll get a build failure or something early on. Maybe we can communicate it a bit better or let's say fix that in cross-font, since it's pretty trivial to fix if you think so.

2020-09-14 13:16 UTC, chrisduerr commented
I don't think this is easy to fix in crossfont. But would you add it to 0.5.0 instead? I forgot this is part of 0.5.0, I must have misremembered.

2020-09-14 13:18 UTC, kchibisov commented
Well, we can fix it for master and then backport to 0.5.1, since 0.5.0 is already out.

2020-09-14 13:30 UTC, chrisduerr commented
How do you suggest we "fix" it though? Adding a feature flag doesn't fix the issue.

2020-09-14 13:40 UTC, kchibisov commented
>How do you suggest we "fix" it though? Adding a feature flag doesn't fix the issue.

I'd send a fix for cross font when I get time.

2020-09-14 13:43 UTC, chrisduerr commented
How do you plan to fix it though?

2020-09-14 14:03 UTC, kchibisov commented
>How do you plan to fix it though?

Check that function exists in build.rs and pass cfg to rustc? that's how you do conditional compilation.

2020-09-14 14:31 UTC, chrisduerr commented
Ah, so you do want to verify the installed freetype version. That's okay I guess.

2020-09-22 20:06 UTC, kchibisov requested changes

2020-09-22 20:06 UTC, kchibisov commented on CHANGELOG.md
> +- Minimum FreeType version has been bumped to 2.8 on Linux
```suggestion
- Minimum FreeType version has been bumped to 2.8 on Linux/BSD
```

2020-09-22 20:10 UTC, kchibisov approved these changes

2020-09-22 20:42 UTC, merged