Draft : Add pollling for a new config to watch when config is deleted
alacritty/alacritty pull request #4322
Opened 2020-10-20 06:21 UTC by oknozor

Hello , this is my first PR to alacritty so I have a few questions : 
- do this needs to be documented in changelog.md  ? 
- shall I bump the version (again I am not sure) ? 

This addresses #2237. 
Regarding the implementation I am not sure what I wrote is a 100% correct : 

- Is it safe to not resolve symlinks ? 
  ```rust
              if path.symlink_metadata().is_ok() {
                  Symlink(path.clone())
              } else {
                  ConfigPath::Path(path.clone())
              }
  ```   
  The idea here is to keep symlinks in place instead of following them. This way when config is unlinked we can wait for it to be re-linked. Symlink paths are not canonicalized in the next step, instead they are checked with `Path::exist`, could this have potential side effects ? 

- How long should we wait for config to be recreated ? 
  I have set a timeout of 6s with 100ms steps, is this appropriate ?

Let me now if anything needs to be changed.

2020-10-20 16:34 UTC, chrisduerr requested changes
I don't see why we would jump through so many hoops just to detect if a config might have been replaced or not. Especially because this still doesn't make symlinks work properly.

Also that polling rate is way too high anyways, at that point the user's system basically under load when doing nothing.

So why special case symlinks when it doesn't help with symlinks anyways? At that point we're just always watching the parent directory which we could have been doing from the beginning then (but we obviously don't want to).

Also why do you start watching all parent directories after having figured out that one of the files must have been replaced? At that point we'd already have our file.

2020-10-20 17:33 UTC, oknozor commented
@chrisduerr 

>  polling rate is way too high anyways

Ok I will change this, what would be a correct polling rate then ?


>  point we'd already have our file

I will also make the required changes to watch only the removed file.

>  So why special case symlinks when it doesn't help with symlinks 

Regarding this one I am not sure to understand why this doesn't help with symlinks. 
This I what I understand so far :  
 - `std::fs::canonicalize` resolve symlinks. 
  ```rust
      let path = std::fs::canonicalize("/home/okno/.config/alacritty/alacritty.yml").unwrap();
      assert_eq!(path, PathBuf::from("/home/okno/dotfiles/.dots/alacritty/alacritty.yml"));
  ```

By having a special case for them we can directly watch for the symlink and not the referenced file : 

- Given alacritty started with the following config symlinked.
  `.config/alacritty -> /home/okno/dotfiles/.dots/alacritty`
- And the config is unlinked then relinked to another config.
  `alacritty -> /home/okno/dotfiles/.dots/alacritty2`

If we are watching for changes in `/home/okno/dotfiles/.dots/alacritty`, we can never find if the symlink is now referencing another file. 
 
That's why I added this special case. Could you explain why this is  a problem ?

2020-10-20 18:18 UTC, chrisduerr commented
> Regarding this one I am not sure to understand why this doesn't help with symlinks.

Have you tested your code?

2020-10-20 18:22 UTC, oknozor commented
Yes I works like a charm for me, I am able to unlink/relink config and it reloads as expected.

2020-10-20 18:29 UTC, chrisduerr commented
> Yes I works like a charm for me, I am able to unlink/relink config and it reloads as expected.

It works like a charm? It does not reload the configuration file anymore when you edit the symlinked file. It performs worse for symlinks than the latest master.

2020-10-20 18:33 UTC, oknozor commented
Relinking works but editing the symlink does not update indeed, sorry I missed this. I'll try to fix it.

2020-10-20 19:04 UTC, kchibisov requested changes
I'm against of adding a polling approach and approach that adds more complexity to supervising. If anything we can add explicit binding to force config reload and research, and if it notices that the previous config no longer accessible via default path, or just reload if it's still there.

2020-10-20 19:35 UTC, oknozor commented
@chrisduerr  I have updated to make the config reload correctly when relinking or editing the file. 


> If anything we can add explicit binding to force config reload and research

@kchibisov  
Where and how should that be implemented ?

2020-10-22 04:47 UTC, kchibisov commented
>Where and how should that be implemented ?

I suggest to add an `ReloadConfig` binding for `key_bindings`, and leave the current polling alone, adding more complexity to it isn't what everyone wants to maintain for very small amount of users.

So to implement it you'd need to add that binding to `alacritty/src/config/bindings.rs`.

Then you should add handling into `alacritty/src/input.rs`. The implementation of that binding could be done in a following way:


- Get current config logical path (not sure if it's stored anywhere, may require storing)`
- Try to load config from the current logical path, if the physical path to that config differs to the current config physical path start watching new config and drop watching of the old one
- Reload config, could be done via issuing `Event::ConfigReload` or we may call to `reload_config` function from event.rs directly, though it could require moving it a bit.

The most complicated part here is recreating or updating the config watcher thread. With the current model it seems like recreating is what should be performed. I feel like the less complex is recreating config watcher, since for informing thing you'd need something like `mio`, though we already depend on it...

I'm not sure that the name should be just `ReloadConfig`, but I guess we can figure that out later, maybe `ForceConfigReload`.

2021-08-18 09:19 UTC, chrisduerr commented
There has been some work to better support symlinks and a polling approach has never been a particularly great option. So closing as resolved. For even more complex scenarios I'd recommend something like #5313.

2021-08-18 09:19 UTC, closed without merging