Increase font size in CSD decorations on Wayland
alacritty/alacritty pull request #4454
Opened 2020-11-21 20:06 UTC by kchibisov

Winit changed the default font size for CSD from 17pt to 11pt, so
restoring it, since it's way too small.

2020-11-21 20:11 UTC, kchibisov commented
Just a reference on how it looks, it's also affected correctly by DPI scaling.

![picture](https://user-images.githubusercontent.com/27620401/99886599-d35b9d80-2c4e-11eb-8c4f-276a41d11b0c.png)

2020-11-21 20:36 UTC, chrisduerr commented
What are the plans for winit? I'd like to see this happen in winit before Alacritty so I can consider if it's even worth adding a workaround to Alacritty.

Also by opening this PR I'd assume you want to include this into 0.6.0 preliminarily? I think I'm personally slightly against this and I'd rather release 0.6.0 as-is.

2020-11-21 20:36 UTC, chrisduerr requested changes
What are the plans for winit? I'd like to see this happen in winit before Alacritty so I can consider if it's even worth adding a workaround to Alacritty.

Also by opening this PR I'd assume you want to include this into 0.6.0 preliminarily? I think I'm personally slightly against this and I'd rather release 0.6.0 as-is.

2020-11-21 20:39 UTC, kchibisov commented
>Also by opening this PR I'd assume you want to include this into 0.6.0 preliminarily? I think I'm personally slightly against this and I'd rather release 0.6.0 as-is.

As it was already mentioned it was regressed from 17 to 11, and since it's 17 in sctk, it makes sense to restore it here, winit will be updated to 17 eventually.

2020-11-21 22:54 UTC, kchibisov commented
>What are the plans for winit? I'd like to see this happen in winit before Alacritty so I can consider if it's even worth adding a workaround to Alacritty.

Added to winit https://github.com/rust-windowing/winit/commit/165e51d850eaff84083d7976b39231ca46c293b2

2020-11-22 01:18 UTC, chrisduerr approved these changes

2020-11-22 01:20 UTC, merged