Fix scrolling region performance with fixed lines at top and bottom
alacritty/alacritty pull request #4459
Opened 2020-11-22 23:54 UTC by chrisduerr

2020-11-22 23:55 UTC, chrisduerr commented
Performance results:

![tmp](https://user-images.githubusercontent.com/8886672/99920827-24869280-2d1e-11eb-9758-83d183a49e3d.png)

2020-11-22 23:57 UTC, chrisduerr commented on alacritty_terminal/src/grid/mod.rs
> +        //  outside of the alt screen anyways.
@kchibisov This comment talks about the same thing we've discussed on IRC. Generally I'd say that the performance is significantly better for the purpose of this PR, while not touching the performance in other areas much.

Do you think there's some other approach that should be evaluated? If so, what would you suggest? I've tried to create a single thing that fixes everything, but if we wanted to implement multiple different variations we'd probably need at least three. One optimized for primary screen scrolling, one for alt screen with the fixed lines and then one fallback that can handle everything but is slow.

2020-11-27 05:28 UTC, kchibisov requested changes

2020-12-08 18:22 UTC, kchibisov approved these changes

2020-12-10 02:10 UTC, merged