Draw selection below Vi cursor when it's hidden
alacritty/alacritty pull request #4476
Opened 2020-11-25 02:23 UTC by kchibisov

2020-11-25 02:45 UTC, chrisduerr requested changes

2020-11-25 02:45 UTC, chrisduerr commented on alacritty_terminal/src/term/mod.rs
> +    fn renderable_cursor<C>(&self, config: &Config<C>, show_cursor: bool) -> RenderableCursor {
Hiding it here rather than the iterator actually makes a lot more sense anyways.

2020-11-25 02:45 UTC, chrisduerr commented on alacritty_terminal/src/term/mod.rs
>              CursorShape::Hidden
This isn't correct though, is it? If `SHOW_CURSOR` isn't set, the vi mode cursor must not be hidden. That's at least one of the reason for the `!vi_mode` check and it looks like you break that here?

2020-11-27 15:14 UTC, chrisduerr approved these changes
LGTM.

2020-11-28 01:01 UTC, merged

2020-12-05 12:38 UTC, rudyscat commented
Lo creo