Update IME composition preview position
alacritty/alacritty pull request #4636
Opened 2020-12-31 12:11 UTC by HelloWorld017

## Changes
* Fix IME composition preview not appearing on Windows
  * Although the [`set_ime_position`](https://docs.rs/winit/0.24.0/winit/window/struct.Window.html#method.set_ime_position)  is supported on Windows, it was disabled. So, it has been enabled.
* Add `cursor.ime_offset` option to set the position of IME composition preview
  * Originally, the IME composition position was one line down from the cursor position. As it is quite uncomfortable to input Hangul, a new option to set the offset is added.

## Screenshots
[![Screenshot](https://i.imgur.com/QVUrDCE.png)
(Click here to play)](https://imgur.com/a/AdclGQ3)

## Tested On
* Windows 10 (1809) + (MS Korean Input, Google Japanese Input)
* ArchLinux + X11 + fcitx (Hangul, Mozc)

2020-12-31 13:24 UTC, chrisduerr requested changes
Good catch, seems like this wasn't added back when IME was enabled for Windows.

> Add cursor.ime_offset option to set the position of IME composition preview 

Please don't just add new features in unrelated PRs. I personally don't see a value in this option and even if there was one it shouldn't be added in this PR.

2021-01-04 08:41 UTC, HelloWorld017 commented
> Please don't just add new features in unrelated PRs.

Sorry for inconvenience! I'll remove that part and force-push.

2021-01-04 09:28 UTC, chrisduerr requested changes

2021-01-04 09:28 UTC, chrisduerr commented on CHANGELOG.md
> +- IME composition preview not appearing on Windows
This needs to go into the 0.8.0-dev release list. I've just made a PR to bump the master to the new version (https://github.com/alacritty/alacritty/pull/4659), once that's merged you can rebase on to that and add it in the proper place.

2021-01-12 12:28 UTC, chrisduerr requested changes

2021-01-12 12:28 UTC, chrisduerr commented on CHANGELOG.md
> +- IME composition preview not appearing on Windows
Wait, there wasn't any IME support before this, right?

So this should probably be `- IME support on Windows` in the `Added` section.

2021-01-15 08:48 UTC, chrisduerr approved these changes
Thanks for the PR.

2021-01-15 08:48 UTC, merged