Update fish completions
alacritty/alacritty pull request #4699
Opened 2021-01-13 10:24 UTC by ammgws

Flags removed in https://github.com/alacritty/alacritty/commit/07684281901b8d287221ade9b7c93a0f437a26f1

2021-01-13 10:27 UTC, chrisduerr requested changes
Huh, the completions must have been forgotten when the CLI changed.

Would you mind fixing the other completion scripts too? Otherwise I'd add that myself.

2021-01-13 10:56 UTC, ammgws commented
I don't use bash but it seemed trivial enough so I gave it a shot.

2021-01-13 10:59 UTC, chrisduerr requested changes
You removed all the old options, however it is missing the new `-o/--option` option. So please add that and add a changelog entry in the `Packaging` section.

2021-01-17 09:45 UTC, chrisduerr requested changes

2021-01-17 09:45 UTC, chrisduerr commented on extra/completions/_alacritty
> +  "(-o --option)"{-o+,--option=}"[override config file options (example: cursor.style=Beam)]:option" \
It looks like examples/defaults are not provided in any other completion documentation, which makes some sense. So I'd advocate for removing it here too. So just `override config file options` should be sufficient.

2021-01-17 09:45 UTC, chrisduerr commented on extra/completions/_alacritty
> +  "(-o --option)"{-o+,--option=}"[override config file options (example: cursor.style=Beam)]:option" \
The options can also be specified multiple times, which you haven't taken into account. I'd propose just applying the following patch to the zsh completions:

```diff
diff --git a/extra/completions/_alacritty b/extra/completions/_alacritty
index 7f0d989..c97d563 100644
--- a/extra/completions/_alacritty
+++ b/extra/completions/_alacritty
@@ -15,6 +15,6 @@ _arguments \
   "--embed=[define the X11 window ID (as a decimal integer) to embed Alacritty within]:windowId" \
   "(-e --command)"{-e,--command}"[execute command (must be last arg)]:program: _command_names -e:*::program arguments: _normal" \
   "--config-file=[specify an alternative config file]:file:_files" \
-  "(-o --option)"{-o+,--option=}"[override config file options (example: cursor.style=Beam)]:option" \
-  "(-t --title)"{-t+,--title=}"[define the window title]:title" \
+  "*"{-o=,--option=}"[override config file options]:option" \
+  "(-t --title)"{-t=,--title=}"[define the window title]:title" \
   "--working-directory=[start shell in specified directory]:directory:_directories"
```

2021-01-17 10:15 UTC, chrisduerr requested changes

2021-01-17 10:15 UTC, chrisduerr commented on extra/completions/alacritty.fish
> +  -d "Override config file options [example: cursor.style=Beam]"
Oh I missed this last time, but the same thing as the zsh suggestions applies here too of course.

```suggestion
  -d "Override config file options"
```

2021-01-17 10:35 UTC, ammgws commented
Sorry about all the back and forth. Hopefully that does it.

2021-01-17 11:10 UTC, chrisduerr approved these changes
Thanks for your work.

2021-01-17 11:22 UTC, merged