change windows default url_launcher
alacritty/alacritty pull request #4895
Opened 2021-03-13 14:41 UTC by fuzzmz

When clicking on a link on windows we don't want to launch Explorer.

Using `cmd /c start "" $LINK/$PATH` opens files and protocols with
their default programs.

Fixes #4885

2021-03-13 17:31 UTC, 2e0gzzdates approved these changes

2021-03-14 01:57 UTC, chrisduerr requested changes
This needs changes in the alacritty.yml and a changelog entry.

2021-03-15 10:31 UTC, fuzzmz commented
@chrisduerr, done.

2021-03-15 14:27 UTC, chrisduerr approved these changes

2021-03-15 14:27 UTC, merged