Keep viewport in place when resizing
alacritty/alacritty pull request #4919
Opened 2021-03-25 19:30 UTC by st3iny

Fixes #4879

First of all, I'd like to thank you for maintaining the most awesome terminal emulator out there. Keep it up :)

My code anchors the viewport at the last visible line. This corresponds to my intuition of how terminal emulators should work. If you want it anchored at the first visible line or have another approach at this issue feel free to leave a comment.

Your feedback is appreciated.

2021-03-25 23:17 UTC, chrisduerr commented
The code doesn't seem quite right and there are a lot of edgecases, but I'll try to take a look after #4907 is done.

2021-03-30 23:26 UTC, chrisduerr requested changes
Could you rebase your PR on top of the latest master?

2021-03-31 07:49 UTC, st3iny commented
Done. Here is a little demonstration of my changes in action:


https://user-images.githubusercontent.com/1479486/113108898-c4d95000-9205-11eb-831b-5d3b4010e95f.mp4

2021-03-31 18:47 UTC, chrisduerr approved these changes
Looks good, thanks.

I've decided to fix a crash I've noticed due to my previous commit and added a changelog message, but the resizing itself worked just fine.

2021-03-31 19:11 UTC, merged