Stop basing focused match color on matched colors
alacritty/alacritty pull request #5025
Opened 2021-04-29 16:07 UTC by nixpulvis

Pending discussion and CHANGELOG entry.

fixes #5022

2021-04-29 16:58 UTC, chrisduerr requested changes
Fix comments, add changelog, change defaults of `focused_match` in yaml and code. Then it should be good to go.

2021-04-29 17:03 UTC, nixpulvis commented
I really don't like the way this looks by default now however:

![screenshot-2021-04-29T17:00:36Z](https://user-images.githubusercontent.com/715947/116589928-2c5ceb00-a8eb-11eb-9ffe-a9a86483abc6.png)

Trying to determine which of these is focused is quite hard.

2021-04-29 17:05 UTC, chrisduerr commented
> I really don't like the way this looks by default now however:

As I've said, the defaults need to be changed they're currently incorrect. And if you're just talking about 'your defaults', that really doesn't matter.

2021-04-29 17:26 UTC, nixpulvis commented
I'm thinking this might be a good default, with the matched text background in red, and the focused match inverted so-as to be consistent with selections:

Colored text focused (first `foo`):
![screenshot-2021-04-29T17:23:23Z](https://user-images.githubusercontent.com/715947/116592702-4ba94780-a8ee-11eb-8aba-7ff721496401.png)

Default foreground text focused (3rd `foo`):
![screenshot-2021-04-29T17:23:33Z](https://user-images.githubusercontent.com/715947/116592719-51069200-a8ee-11eb-9d21-c992e73bedf8.png)

2021-04-29 17:53 UTC, chrisduerr commented
The focused match color should be the inverse of the normal text color.

2021-04-29 17:55 UTC, nixpulvis commented
> The focused match color should be the inverse of the normal text color.

Isn't it? Or do you mean always like in the second image? If so, why? Isn't it nice that it's consistent with the way selections look in general?

2021-04-29 17:58 UTC, chrisduerr commented
It's nice to keep things simple. There's no need to over-complicate this. The default config should behave the same way and the best way to do this is to just invert the normal match colors manually for the focused match.

2021-04-30 16:23 UTC, chrisduerr requested changes

2021-04-30 16:23 UTC, chrisduerr commented on alacritty.yml
> +    #  foreground: '#ff0000'
I've told you that I don't want to change this, didn't I? I'm not sure how to make myself more clear on how I'd suggest to resolve this.

2021-04-30 16:26 UTC, lockheadone commented
https://github.com/alacritty/alacritty/pull/5025/files/70b42ab429dc103cb940809c530c0e04c38f3782

2021-04-30 17:03 UTC, nixpulvis commented
> https://github.com/alacritty/alacritty/pull/5025/files/70b42ab429dc103cb940809c530c0e04c38f3782

Was there a point to this link?

2021-04-30 17:04 UTC, chrisduerr commented on alacritty.yml
> +    #  foreground: '#ff0000'
There is zero reason to change the defaults in this PR. The requested change is completely unrelated to that. I'm not sure why you're derailing this PR with an unrelated change.

2021-04-30 22:00 UTC, chrisduerr approved these changes

2021-04-30 22:16 UTC, merged