Add configuration flag for right-click selection
alacritty/alacritty pull request #5194
Opened 2021-05-30 15:34 UTC by 101100

This add a flag to the `selection` section of the configuration file called `right_click_expand` that defaults to `true`.  If it is set to `false`, the right-click behaviour that expands the selection is disabled, allowing other actions to be performed involving the selection without it changing.

Fixes #4132

2021-05-31 00:15 UTC, chrisduerr requested changes
I'm not really interested in just making this a configuration option to toggle the default behavior. If you wanted to make this configurable, it should be made into a binding. This way is just messy.

2021-05-31 15:54 UTC, 101100 commented
I understand not wanting to add a bunch of one-off flags.

How about these changes instead:

- Make some mouse-exclusive actions called `ExpandSelectionSimple`, `ExpandSelectionBlock`, `ExpandSelectionSemantic`, and `ExpandSelectionLines`. Mouse exclusive so I don't need to change `self.expand_selection` to handle vi mode or anything else.
- Add two new mouse modifiers `DoubleClick` and `TripleClick` for use in any mouse binding.
- Remove the `on_right_click` function and expand the default configuration with these extra rules:

```yml
mouse_bindings:
  - { mouse: Right, action: ExpandSelectionSimple }
  - { mouse: Right, action: ExpandSelectionBlock, mod: Control }
  - { mouse: Right, action: ExpandSelectionSemantic, mod: DoubleClick }
  - { mouse: Right, action: ExpandSelectionLines, mod: TripleClick }
```

2021-05-31 23:45 UTC, chrisduerr commented
That sounds excessively complicated for the desired effect. Especially because the right click to paste is hardly useful with MMB doing the same (or similar) on other platforms.

2021-06-01 03:59 UTC, 101100 commented
It would allow full customization, though.  It seems that to solve #4132 either you need a simple toggle or full customization.  Is there a middle-ground you were considering?  Two possibilities not available now that full customization would allow:

- the right mouse button without modifiers could be configured to expand selection by lines instead of to the exact position
- a middle double click could minimize the window or do any other action

If you aren't interested in this change, then I'll just leave it as-is.  (I'm still pretty happy with Alacritty and thank you for it!)  As I said in #4132, I would like to be able to remove the right-click expand selection as a middle click is just not available on my trackpad.

2021-06-01 04:22 UTC, 101100 commented
I looked again and in the liked issue you mentioned ignoring the default behaviour if a configured mouse event occurs.  In that case, then if `process_mouse_bindings` finds an appropriate binding it could return a boolean value of true to `mouse_input` and then it would not call `on_mouse_press` (or it would with a flag so we still get the possibility of double and triple clicks). I could do that if you prefer.

2021-07-03 20:29 UTC, chrisduerr commented
Just as a little update: There have been **a lot** of requests for this, so I do believe that some form of configurability is probably advisable here. I've just not decided *how* this should best be done.

2021-07-05 21:50 UTC, 101100 commented
OK, let me know once you've decided.  I'm happy to help out once the design is complete.

2021-07-14 00:34 UTC, chrisduerr requested changes
I think the best solution would be to make `ExpandSelection` an `action` that can be selected for mouse bindings.

Would you mind implementing this? It should be fairly trivial hopefully.

2021-07-17 17:02 UTC, 101100 commented
Created a new PR with the suggested different approach.

2021-07-17 17:02 UTC, closed without merging