Fix ScrollHalfPageUp action's regression
alacritty/alacritty pull request #5235
Opened 2021-06-13 17:48 UTC by a5ob7r

The regression is that cursor doesn't move to topmost on scrollback buffer and keep it near bottommost when invokes ScrollHalfPageUp action of vi mode even if repeats it. Also it is happen even if vi mode cursor is on above bottommost when in topmost viewport. So looks like that the cursor moves to bottommost line on topmost viewport even though try to move cursor to upper line.

This regression is came from 3bd5ac2 which introduces unified index type. The reason why is that old index type for viewport minimum index is zero, but new index type minimum one is zero or minus value. So vi mode cursor scrolling for new index type need to consider the new rule.  So use `Boundary::Grid`, which is range of entire grid, as cursor point clamping instead of `Boundary::Cursor`, which is range of viewport.

Following movie shows a situation of this regression.

In this movie, I do some steps like below.
(And with default Alacritty keybinding configs.)

Steps
1. Enter vi-mode.
2. Invoke ScrollHalfPageUp action by `Ctrl-U` repeatedly until rearch topmost of scrollback buffer.
3. Move vi mode cursor to a little upper line by `K` repeatedly.
4. Back to `2.`.

https://user-images.githubusercontent.com/12132068/121816736-3cbcff80-ccb8-11eb-9e93-4a122f0a6ac1.mp4

2021-06-13 17:54 UTC, chrisduerr requested changes
Looks good, but since this bug is part of the latest stable release, we need a changelog message.

2021-06-14 04:07 UTC, a5ob7r commented
@chrisduerr Done!

2021-06-15 20:20 UTC, chrisduerr commented
Even after the patch the cursor still seems to jump to the first column, this shouldn't be the case. Are you able to reproduce this behavior?

2021-06-16 05:35 UTC, a5ob7r commented
Does `first column` mean `first occupied column`? If so, yes. But I think that it is right behavior due to same one on vi/vim.

```
// `|` indicates column(cursor) position.

|  aaa // index 0 column
  |aaa // first occupied column
```

2021-06-16 08:53 UTC, chrisduerr approved these changes

2021-06-16 08:55 UTC, merged

2021-06-16 09:11 UTC, a5ob7r commented
Thank you!