Bump glutin to 0.28.0
alacritty/alacritty pull request #5650
Opened 2021-12-02 11:45 UTC by kchibisov

2021-12-02 23:30 UTC, afh commented
➕ Very much looking forward to this update as glutin 0.28.0 will update [winit](https://github.com/rust-windowing/winit) to 0.26.0, which will update [smithay-client-toolkit](https://github.com/Smithay/client-toolkit) to at least 0.15.1 and will address #5422 🙂 🎉

2021-12-03 03:26 UTC, chrisduerr requested changes
I believe CONTRIBUTING.md also contains the MSRV.

2021-12-03 03:26 UTC, chrisduerr commented on CHANGELOG.md
> +- Wayland client side decorations were simplified
I like the way "simplified" sounds. It's a feature! :smile:

2021-12-03 03:27 UTC, chrisduerr approved these changes

2021-12-03 03:50 UTC, merged