Fix CreateNewWindow CLI fallback
alacritty/alacritty pull request #5699
Opened 2021-12-18 18:41 UTC by chrisduerr

The existing behavior for the new CreateNewWindow actions was to always
pass in their own options, which would discard the existing options
configured on the terminal's PTY config.

To fix this the behavior for CreateNewWindow is now the same as for the
initial window creation, the config values are overwritten conditionally
based on their individual presence in the CLI options.

However this also means that all temporary CLI options set on the
"master" Alacritty instance are inherited by all future windows.

Fixes #5659.

2021-12-18 22:42 UTC, kchibisov requested changes
I was thinking whether to do so or not when implementing it. Right now I think that we should inherit options.

>However this also means that all temporary CLI options set on the
"master" Alacritty instance are inherited by all future windows.]

Yeah, but this isn't working right now on your PR with `hold` flag. I'm not sure how we should handle them and overwriting options. Initially I've used `Option` to indicate that nothing was provided. One solution would be to wrap everything on `TerminalOptions` in `Option`.

2021-12-18 23:52 UTC, chrisduerr commented
> Yeah, but this isn't working right now on your PR with hold flag. I'm not sure how we should handle them and overwriting options. Initially I've used Option to indicate that nothing was provided. One solution would be to wrap everything on TerminalOptions in Option.

That's a good point, but this is trivial to fix. `false` for structopt is just the same as `None`, since it's a flag. So no need to wrap the `hold` in an `Option`, clap also just really doesn't like that. False is the same here.

2021-12-19 07:24 UTC, kchibisov commented
I think the problem here with `hold` is a bit more complicated. The thing is that when you pass `hold` on a CLI to the main application there's no way to disable it anymore. This applies to every flag like `hold`. The solution could be to discard all boolean flags back to default values (like it was initially) or add extra flag like `no-hold` (and that would apply to every flag).

2021-12-20 15:32 UTC, kchibisov commented
>I'd say there are two reasonable options: Either we keep it the way it currently is, the base CLI flags are basically treated like config settings and inherited everywhere. The other option is to discard all CLI flags from the original client, then we'd probably have to store config/cli separately.

I think discarding for new windows (the way it originally was on this PR) is fine for such flag. Not all, but only boolean flags like hold, since we already have a `hold` flag to pass.

2021-12-20 15:48 UTC, chrisduerr commented
> I think discarding for new windows (the way it originally was on this PR) is fine for such flag. Not all, but only boolean flags like hold, since we already have a hold flag to pass.

Discarding only *some* flags seems rather terrible though. At that point there's no consistency for the user?

Also how do you suggest this be implemented, would you discard it completely, ignoring the configuration file option? Or store the CLI/Config stuff separately and only override the former?

2021-12-20 15:58 UTC, kchibisov commented
>Also how do you suggest this be implemented, would you discard it completely, ignoring the configuration file option? Or store the CLI/Config stuff separately and only override the former?

Use config option by default, unless CLI option is passed. if `--hold` was passed on CLI apply hold, however if you create a new window, don't apply hold to it, unless it's presented in a config or user explicitly specified `--hold` on CLI for the new window.

2021-12-20 16:57 UTC, chrisduerr commented
> Use config option by default, unless CLI option is passed. if --hold was passed on CLI apply hold, however if you create a new window, don't apply hold to it, unless it's presented in a config or user explicitly specified --hold on CLI for the new window.

Yeah, sounds reasonable. Basically treat a new window the same way we'd treat a new instance.

2021-12-22 19:05 UTC, chrisduerr commented
@kchibisov If you're around still do you mind testing to see if everything now works as you would expect?

2021-12-23 02:49 UTC, kchibisov approved these changes

2021-12-23 10:23 UTC, merged

2021-12-23 10:33 UTC, chrisduerr commented
Was kinda scared you just merged the PR with the original commit message, but turns out you're way ahead of me in that regard. Great work.