Account for absolute WAYLAND_DISPLAY paths
alacritty/alacritty pull request #5890
Opened 2022-02-15 20:33 UTC by mahkoh

If WAYLAND_DISPLAY contains a '/', we have to replace with with another
character before using WAYLAND_DISPLAY as a path component.

2022-02-15 23:44 UTC, chrisduerr requested changes
Seems like a sensible workaround. Out of curiosity, did you actually run into this in the wild or did you have to manually create this scenario?

I'd be curious which compositor uses slashes in their `WAYLAND_DISPLAY`.

Also this should be documented in the changelog, because I'd assume some users might actually run into this if there's compositors out there using slashes in `DISPLAY`.

2022-02-16 13:48 UTC, mahkoh commented
> Seems like a sensible workaround. Out of curiosity, did you actually run into this in the wild or did you have to manually create this scenario?

I'm currently writing a new wayland that currently uses an absolute path it WAYLAND_DISPLAY.

2022-02-16 20:18 UTC, kchibisov approved these changes

2022-02-16 20:55 UTC, chrisduerr approved these changes

2022-02-16 21:15 UTC, merged