Don't load font twice during display creation
alacritty/alacritty pull request #5894
Opened 2022-02-16 22:24 UTC by kchibisov

This commit finishes the effort from a64553b to avoid reloading font
twice during startup, since the original issue is with getting font
metrics without building the glyph cache.

--
I've also renamed dpr to scale factor, since I don't really like dpr name in general for UI rendering. Since it's a DPR in its nature only on X11, but on other platforms it's a UI scale factor.

2022-02-16 22:25 UTC, kchibisov commented on alacritty/src/display/mod.rs
> +        }
Do we even need this benchmarking?

2022-02-17 09:59 UTC, chrisduerr requested changes
There's still a mention of DPR in `alacritty/src/renderer/mod.rs:354`.

2022-02-17 09:59 UTC, chrisduerr commented on alacritty/src/display/mod.rs
> +        // If the scaling factor changed update the glyph cache and resize latter on.
```suggestion
        // If the scaling factor changed update the glyph cache and mark for resize.
```

2022-02-17 09:59 UTC, chrisduerr commented on alacritty/src/display/mod.rs
> +        } else {
No more estimated correctly log?

2022-02-17 09:59 UTC, chrisduerr commented on alacritty/src/display/mod.rs
>          }
I'm not sure it's appropriate to merge this as-is? A fine-grained benchmark like this doesn't provide much value and our log messages already print timestamps anyway.

2022-02-17 09:59 UTC, chrisduerr commented on alacritty/src/display/mod.rs
> +        if let Some(dimensions) = should_resize.then(|| dimensions).flatten() {
dimensions.filter(|_| should_resize) shouldn't require .flatten, so I think it's a little neater maybe?

2022-02-17 14:31 UTC, kchibisov commented on alacritty/src/display/mod.rs
> +        } else {
Yes, I don't see why we'd need it.

2022-02-17 14:34 UTC, kchibisov commented
>There's still a mention of DPR in alacritty/src/renderer/mod.rs:354.

That's crossfont API.

2022-02-17 22:05 UTC, chrisduerr approved these changes

2022-02-17 22:27 UTC, merged