Overline (SGR 53/55) support
alacritty/alacritty pull request #6122
Opened 2022-06-09 13:40 UTC by dropbear32

The overline attribute (SGR code 53 to enable / 55 to disable) is currently unsupported by Alacritty. This PR adds support for those codes.

---

While overlines are properly drawn by this commit if they are switched to be (e.g.) SGR 1, for some reason if SGR 53 or 55 is passed, they are not present in the parameter list passed to `csi_dispatch`, so this commit is non-functional at present. As I do not know Rust, any help in figuring this bug out would be appreciated.

2022-06-09 16:27 UTC, chrisduerr requested changes
See https://github.com/alacritty/alacritty/issues/5988 and https://github.com/alacritty/alacritty/issues/1647.

2022-06-09 16:27 UTC, closed without merging

2022-06-10 00:57 UTC, atirit commented
From what I understood reading those issues, "low priority" meant that the feature was not high on anyone's list of things to work on, and I will note the following:

> So if people aren't using this anymore, I'd say good riddance.

I use these escape codes in a TUI I'm writing, so they're not entirely unused and they're not low-priority for me (hence why I spent time working on this PR).

Please also see [my comment](https://github.com/alacritty/alacritty/issues/5988#issuecomment-1145525597) in #5988.

If Alacritty explicitly does not and will not support certain escape codes, then a different PR should be merged specifying that in the documentation.

2022-06-10 04:28 UTC, chrisduerr commented
> If Alacritty explicitly does not and will not support certain escape codes, then a different PR should be merged specifying that in the documentation.

Feel free, I'd be happy to accept that.

2022-06-10 12:01 UTC, atirit commented
> this commit is non-functional at present

*on Windows.

The reason this patch does not work on Windows is because ConPTY seems to remove escape sequences it does not recognize, and the version shipped with (my build of) Windows is older than the version that supports SGR 53/55. This is, as far as I'm aware, not fixable without bundling/linking against a newer version of ConPTY, which has unfortunately been explicitly rejected in #4501.