support hexadecimal input for `--embed`
alacritty/alacritty pull request #6158
Opened 2022-06-26 18:06 UTC by ssiyad

https://github.com/alacritty/alacritty/issues/6145

2022-06-26 20:41 UTC, kchibisov requested changes
In general the approach looks good.

However I'd probably write something like

```diff
diff --git a/alacritty/src/cli.rs b/alacritty/src/cli.rs
index be377700..babdcafa 100644
--- a/alacritty/src/cli.rs
+++ b/alacritty/src/cli.rs
@@ -100,7 +100,13 @@ impl Options {
         }
 
         config.window.dynamic_title &= self.window_options.window_identity.title.is_none();
-        config.window.embed = self.embed.as_ref().and_then(|embed| embed.parse().ok());
+        config.window.embed = self.embed.as_ref().and_then(|embed| {
+            embed
+                .starts_with("0x")
+                .then(|| u64::from_str_radix(&embed[2..], 16).ok())
+                .unwrap_or_else(|| embed.parse().ok())
+        });
+
         config.debug.print_events |= self.print_events;
         config.debug.log_level = max(config.debug.log_level, self.log_level());
         config.debug.ref_test |= self.ref_test;
```

And probably put it into `parse_hex_or_decimanl(&str)` function with a test for it. You can look at `parse_class`, so the end result will look like

```rust
config.window.embed = self.embed.as_ref(),and_then(parse_hex_or_decimal)`
```

2022-06-27 17:49 UTC, kchibisov requested changes
Looks good, could you add an entry to `Changed` section in `CHANGELOG.md`, like: `--embed option could accept hexadecimal values by providing `0x`.

Also, you should tune `--help` output, since right now it only states `decimal`, but not hexadecimal starting with `0x`.

2022-06-28 12:26 UTC, chrisduerr requested changes

2022-06-28 12:26 UTC, chrisduerr commented on alacritty/src/cli.rs
> +        .unwrap_or_else(|| input.parse().ok())
I recommend using the `strip_prefix` method here.

2022-06-28 12:26 UTC, chrisduerr commented on CHANGELOG.md
> +- `--embed` could accept hexadecimal values starting with `0x`
This is a new feature, should be moved to `Added`. "could" is also not appropriate here, I recommend the following:

```
 - Accept hexadecimal values starting with `0x` for `--embed`
```

2022-06-28 12:26 UTC, chrisduerr commented on alacritty/src/cli.rs
> +    /// Defines the X11 window ID (as a decimal integer or hexadecimal starting with 0x) to embed Alacritty within.
I think we can do much better than this.

Maybe something like that:

```
/// X11 window ID to embed Alacritty within (decimal or hexadecimal with "0x" prefix).
```

2022-06-28 14:31 UTC, kchibisov commented on alacritty/src/cli.rs
> +fn parse_hex_or_decimal(input: &str) -> Option<u64> {
Seems like we should use `c_ulong` instead of `u64` here.

2022-06-28 18:16 UTC, chrisduerr approved these changes
LGTM

2022-06-28 18:21 UTC, kchibisov approved these changes

2022-06-28 18:22 UTC, merged

2022-06-28 18:22 UTC, ssiyad commented
@chrisduerr @kchibisov As a rust newbie, I couldn't have done this without your guidance. Thank you!