Use timer based rendering instead of vsync
alacritty/alacritty pull request #6175
Opened 2022-06-30 22:49 UTC by kchibisov

Given that alacritty handles all the windows on the main thread using
vsync will result in sequential locks on swap buffers for each window
it'll try to draw at the given time, reducing the frame rate by the
amount of windows being drawn.

Timer based solution solves this since there's no more blocking
involved.

2022-08-11 09:08 UTC, kchibisov commented
It was working quite good in Xwayland, though, not sure how it goes in a multi monitor environment.

2022-08-13 02:19 UTC, chrisduerr commented
While this does improve the rendering rate with 4 windows from ~35FPS to 40-60 FPS, it also decreases the rendering rate with a single window from a steady 144FPS to 60-100FPS. So I think something's not working quite right.

2022-08-13 02:20 UTC, chrisduerr requested changes
See my comment, I don't think this is working properly.

2022-08-13 06:20 UTC, kchibisov commented
Could you retest?

2022-08-13 20:01 UTC, kchibisov commented
Ah, shouldn't work either. The problem is that with high refresh rate you have less time in general and this time you're spending on processing the event queue as well. So to solve this we should account for the event processing as well, not just for rendering.

In general, it's kind of impressing that event processing takes similar amount of time compared to rendering, especially given that we don't have any interactions. Maybe we're flooding a lot or winit on x11 is slow in general?

Besides that, the real solution is vsync source in winit, however we'd need some sort of fallback. In the mean time I'll try to account for the event processing as well and see how it goes.

2022-08-13 20:53 UTC, chrisduerr commented
> In general, it's kind of impressing that event processing takes similar amount of time compared to rendering, especially given that we don't have any interactions. Maybe we're flooding a lot or winit on x11 is slow in general?

I mean we are sending about a billion `Wakeup`s through the event loop when running `yes`, but that isn't limited to X11.

2022-08-15 18:55 UTC, kchibisov commented
Could you retest in a mixed refresh rate environment? I think it should work now, at least it can maintain the frame rate.

2022-08-16 00:10 UTC, chrisduerr commented
Without mixed refresh rate, I've noticed that this patch takes significantly longer to reach the desired framerate than the old version. Which might be problematic since having to wait *seconds* before getting the full refresh rate might not give you your full performance with short-lived processes.

![tmp](https://user-images.githubusercontent.com/8886672/184756073-b0ed46af-4bae-4fda-80d2-c8be4b79c563.png)

![tmp](https://user-images.githubusercontent.com/8886672/184756176-39a46b28-48b2-43fa-becc-58881c62be42.png)

Running with three windows, one on a 60Hz shows some significant instabilities on the 144Hz monitors:

![tmp](https://user-images.githubusercontent.com/8886672/184756489-3f60d7ec-3bf7-4a5c-9ea7-bb6fd7a42f30.png)

Though it is steady on the 60Hz one:

![tmp](https://user-images.githubusercontent.com/8886672/184756515-3416222d-43f7-4799-8438-d00e7b05fe3c.png)

Running three 144Hz windows shows the same results, indicating that it cannot handle three windows at the same time running at 144Hz, while mixing 144/60Hz shouldn't be an issue:

![tmp](https://user-images.githubusercontent.com/8886672/184756894-d9da58f2-6f47-48ee-bf9b-bd23d7ce435c.png)

Sustaining 144 FPS with three separate instances on three 144Hz monitors is not an issue:

![tmp](https://user-images.githubusercontent.com/8886672/184756640-1a012426-82bb-4397-8c92-12b9b609c592.png)

So the massive fluctuations and significant drop in performance is certainly not due to hardware limitations.

2022-09-03 19:40 UTC, trimental commented on alacritty/src/display/mod.rs
> +        // On Waylad frame event should be requested before swaping buffers, since it requires
Typo of wayland

2022-09-03 19:42 UTC, chrisduerr commented on alacritty/src/display/mod.rs
> +        // On Waylad frame event should be requested before swaping buffers, since it requires
One hell of a lad.

2022-09-03 19:44 UTC, trimental commented on alacritty/src/display/mod.rs
> +        // On Waylad frame event should be requested before swaping buffers, since it requires
Practically a full grown man

2022-09-03 20:44 UTC, trimental commented
Sorry for chiming in with an idea on something I know little about; but could you do timer based rendering by having a vector of each unique monitor refresh rate and references to the `has_frame` atomic bool of each window using that rate. So `(16ms, [has_frame#1, has_frame#3, has_frame#5])` and `(8ms, [has_frame#2, has_frame#4])`, and then wake up on events for an interval of 16/3 ms and 8/2 ms and iterate through the atomic bools setting them true. 

At least that way each redraw is spaced as far as possible from the last. Won't the windows naturally just desynchronise into randomly spaced redraws relative to one another no matter what the offset is if you set the interval per window?

2022-09-03 20:53 UTC, kchibisov commented
The timer is per window with the current monitor rate. So other windows shouldn't matter.

2022-09-03 20:54 UTC, trimental commented
Perhaps the reason why it takes time to reach the desired frame rate is because it works better when the windows intervals become desynchronised?

2022-09-03 20:58 UTC, trimental commented
How do you know that each window is drawing at a time when other windows aren't though. I thought that's what causes the drop in fps.

2022-09-03 21:17 UTC, trimental commented
Sorry I just realised that it's the swap_buffers function that blocks for vsync. I thought they were locked in a shared state between windows. 🤦

2022-12-25 07:52 UTC, kchibisov commented
Closing in favor of #6585.

2022-12-25 07:52 UTC, closed without merging