Fix icon decoding on X11
alacritty/alacritty pull request #6369
Opened 2022-09-30 13:25 UTC by Hugal31

glutin is waiting for a RGBA with 8-bit depth, but our icon is 16-bit depth. Normalize the color data when decoding the icon.

Without this, I had a `winit::icon::BadIcon::DimensionsVsPixelCount` when loading the icon on Linux/X11.

2022-10-02 02:45 UTC, chrisduerr commented
Which Alacritty version did you build? I'm not running into any errors on Linux.

2022-10-04 08:58 UTC, Hugal31 commented
I'm trying on the last upstream commit (e9ee8dc). A bisect shows the bug appears since 7d708d5.
You can run with this patch to make the error more visible:
```patch
diff --git a/alacritty/src/display/window.rs b/alacritty/src/display/window.rs
index 6c88f56f..582856e9 100644
--- a/alacritty/src/display/window.rs
+++ b/alacritty/src/display/window.rs
@@ -331,6 +331,11 @@ impl Window {
             Icon::from_rgba(buf, reader.info().width, reader.info().height)
         };

+        #[cfg(feature = "x11")]
+        if let std::result::Result::<&Icon, &glutin::window::BadIcon>::Err(err) = icon.as_ref() {
+            log::error!("could not load icon: {:?}", err);
+        }
+
         let builder = WindowBuilder::new()
             .with_title(&identity.title)
             .with_name(&identity.class.general, &identity.class.instance)
```

I'm using Ubuntu 20.04 with XFCE 4.14 if that helps.

2022-10-04 21:26 UTC, chrisduerr commented
> You can run with this patch to make the error more visible:

Ah okay, so the issue is just that the icon doesn't show up, it doesn't crash or anything?

2022-10-05 02:01 UTC, chrisduerr requested changes
A big reason why this error went undetected is that we just pass `icon.ok()` to `with_window_icon` and thus any error is silently ignored and we just pretend that no icon was specified.

However, we **always** load and decode an icon on X11 and we're certain that this should work without any errors. So to avoid having a silent failure like this in the future, I'd actually change the code to be more verbose here.

We could return a result since we already `expect` the `read_info`, or alternatively we could also `expect` icon decode errors. Generally I think I'd expect returning a Result but I'm not sure if that can be easily handled by the caller.

2022-10-05 07:56 UTC, Hugal31 commented
Yes, this cause no crash, it only silently fails to add the icon. In fact, on my setup, it shows the icon on the window decorator but not on the XFCE desktop miniatures somehow, but I don't know if it is specific to my setup.

I don't think we should return a result. Either we consider this is a "build" (not a runtime) error and panic (by `expect`ing the result), or we consider this can happen log a warning because a missing icon is not a big deal. But if we return a result, we will have to handle it and because this is the function supposed to create the WindowBuilder, we will still be left in a useless state.

Personally i'll go with a warning.

2022-10-05 13:12 UTC, chrisduerr commented
We do **not** want a warning here, since this should **always** succeed. The image we pass in is compiled into our application so it will either always fail or never. If it always fail we want it to be as noisy as possible so we can fix it asap.

2022-10-05 13:13 UTC, chrisduerr approved these changes

2022-10-05 13:14 UTC, merged