Handle GPU resets
alacritty/alacritty pull request #6530
Opened 2022-11-26 20:42 UTC by kchibisov

This should keep alacritty working after the GPU reset getting detected.

2022-11-28 02:32 UTC, kchibisov commented
This branch is blocked, unless I can find a system to reliably test it. Eventually sway will get support for reset recovering, but for now when GPU reset happens system compositor is the first thing that dies so the fact that alacritty will die doesn't matter.

There also will be a driver protocol to handle such a thing.

2023-03-07 22:40 UTC, matu3ba commented
> This branch is blocked, unless I can find a system to reliably test it. Eventually sway will get support for reset recovering, but for now when GPU reset happens system compositor is the first thing that dies so the fact that alacritty will die doesn't matter.

Arcan claims to handle GPU resets + more gracefully. [technical details](https://arcan-fe.com/2017/12/24/crash-resilient-wayland-compositing/). [repo](https://github.com/letoram/arcan)

2023-03-07 22:45 UTC, kchibisov commented
I mean sway will have support for stuff like that eventually, it'll also require a special protocol though.

2025-01-10 19:16 UTC, YaLTeR commented
Got it to recover successfully on an AMD dGPU in a laptop, sway 1.10, kernel 6.11.11.
```
[75.892549293s] [INFO ] [alacritty] GPU reset (innocent)
[75.895038005s] [ERROR] [alacritty] [gl_render] GL_CONTEXT_LOST in context lost
[75.895105231s] [ERROR] [alacritty] [gl_render] GL_CONTEXT_LOST in context lost
[75.895132933s] [ERROR] [alacritty] [gl_render] GL_CONTEXT_LOST in context lost
[75.895157971s] [ERROR] [alacritty] [gl_render] GL_CONTEXT_LOST in context lost
[75.895182176s] [ERROR] [alacritty] [gl_render] GL_CONTEXT_LOST in context lost
[75.895253811s] [ERROR] [alacritty] [gl_render] GL_CONTEXT_LOST in context lost
[75.895281102s] [ERROR] [alacritty] [gl_render] GL_CONTEXT_LOST in context lost
[75.895304166s] [ERROR] [alacritty] [gl_render] GL_CONTEXT_LOST in context lost
[75.895326999s] [ERROR] [alacritty] [gl_render] GL_CONTEXT_LOST in context lost
[75.895357155s] [ERROR] [alacritty] [gl_render] GL_CONTEXT_LOST in context lost
[75.895379908s] [ERROR] [alacritty] [gl_render] GL_CONTEXT_LOST in context lost
[75.903346426s] [INFO ] [alacritty] Running on AMD Radeon RX 6700M (radeonsi, navi22, LLVM 19.1.5, DRM 3.59, 6.11.11-300.fc41.x86_64)
[75.903459529s] [INFO ] [alacritty] OpenGL version 4.6 (Core Profile) Mesa 24.3.2, shader_version 4.60
[75.903480799s] [INFO ] [alacritty] GPU reset notifications are enabled
[75.903500155s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[75.908700058s] [DEBUG] [alacritty] Enabled debug logging for OpenGL
[75.919608000s] [DEBUG] [alacritty] Recovered window WindowId(94729299219344) from gpu reset
[75.935177160s] [DEBUG] [alacritty_terminal] New num_cols is 159 and num_lines is 83
[75.935811363s] [INFO ] [alacritty] Padding: 2 x 2
[75.935873921s] [INFO ] [alacritty] Width: 1276, Height: 1548
```

2025-01-10 19:18 UTC, kchibisov commented
>[75.895357155s] [ERROR] [alacritty] [gl_render] GL_CONTEXT_LOST in context lost

@chrisduerr btw, should we log those as error if we can recover? it does let the user know that gpu crashed, but it just opens message bar...

2025-01-10 19:28 UTC, chrisduerr commented
> should we log those as error if we can recover? it does let the user know that gpu crashed, but it just opens message bar...

What does the user gain by knowing? It's not really Alacritty's responsibility to inform the user about this.

2025-01-10 19:33 UTC, kchibisov commented
>What does the user gain by knowing? It's not really Alacritty's responsibility to inform the user about this.

we just has general handler that does error logging on opengl errors, though, I guess for context loss we can suppress it.

2025-01-10 19:36 UTC, chrisduerr requested changes

2025-01-10 19:36 UTC, chrisduerr commented on alacritty/build.rs
> +        "GL_KHR_robustness",
How widely is this supported?

2025-01-10 19:36 UTC, chrisduerr commented on alacritty/src/display/mod.rs
> +        self.make_current(false);
Are we just not recovering here because it's not necessary? Seems kinda odd to have a parameter solely for the drop impl.

2025-01-10 19:36 UTC, chrisduerr commented on alacritty/src/renderer/mod.rs
> +    fn log_reset_notification_status() -> bool {
Why does this return a boolean?

2025-01-10 19:36 UTC, chrisduerr commented on alacritty/src/display/mod.rs
> +        was_context_reset |= self.renderer.was_context_reset();
Is there a realistic benefit to this not just being inside the `is_current` branch? Sure it might help if the context resets right after the `make_current` call, but that could also happen right after this call, right? So in the end this should only really be necessary if `is_current` is true?

2025-01-10 19:36 UTC, chrisduerr commented on alacritty/src/display/mod.rs
> +        };
```suggestion
        // Attempt to make the context current, if it is not.
        let mut was_context_reset = if is_current {
            false
        } else {
            match self.context.make_current(&self.surface) {
                Err(err) if err.error_kind() == ErrorKind::ContextLost => {
                    info!("Context lost for window {:?}", self.window.id());
                    true
                },
                _ => false,
            }
        };
```

I think a comment here is nice to explain that our goal here is not just checking if the context was reset, but actually performing the make_current call.

2025-01-10 19:36 UTC, chrisduerr commented on alacritty/src/display/mod.rs
> +                    .expect("failed to recreate context.");
```suggestion
                platform::create_gl_context(&gl_display, &gl_config, raw_window_handle)
                    .expect("failed to recreate context.");
```

2025-01-10 19:36 UTC, chrisduerr commented on alacritty/src/display/mod.rs
> +            let gl_display = self.context.display();
This is a pretty big chunk of code inside this conditional. Could probably move it to a function or early-return.

2025-01-10 19:39 UTC, kchibisov commented on alacritty/src/display/mod.rs
> +        self.make_current(false);
yeah, we don't recover since it doesn't matter, otherwise we create render and drop it.

2025-01-10 19:41 UTC, chrisduerr commented on alacritty/src/display/mod.rs
> +        self.make_current(false);
Would *probably* be fine tbh. It's **extremely** unlikely to ever happen anyway.

Like who manages to shut down Alacritty right between rendering at a billion frames a second and a GPU reset? Even if we crash at that point most people would never notice.

2025-01-10 19:52 UTC, kchibisov commented on alacritty/src/display/mod.rs
> +        was_context_reset |= self.renderer.was_context_reset();
I feel like it could lie/desync/not propagate, it's opengl at the end of the day.

2025-01-10 21:44 UTC, chrisduerr commented on alacritty/src/display/mod.rs
> +        was_context_reset |= self.renderer.was_context_reset();
But isn't the same true for this function too? How likely are the two to be different?

2025-01-10 21:45 UTC, chrisduerr requested changes

2025-01-10 21:45 UTC, chrisduerr commented on alacritty/src/renderer/mod.rs
> +        // If robustness is not supproted, don't use its functions.
```suggestion
        // If robustness is not supported, don't use its functions.
```

2025-01-11 04:43 UTC, kchibisov commented on alacritty/src/display/mod.rs
> +        was_context_reset |= self.renderer.was_context_reset();
The context is done by WSI, but the OpenGL is by driver itself, though, eventually the `is_current` path will be triggered.

2025-01-11 05:39 UTC, chrisduerr approved these changes

2025-01-11 05:47 UTC, merged