create new windows with Cmd+N by default
alacritty/alacritty pull request #6648
Opened 2023-01-26 19:12 UTC by chrisduerr

This changes the default Cmd+N binding on macOS to create a new window rather than spawning a new instance.

Initially this change was held back for further testing of the multi-window feature. At this point all significant issues found with it have been fixed so it should be ready for prime-time now.

2023-01-26 23:33 UTC, kchibisov requested changes
Given that you change default behavior you should update the changelog entry.

2023-01-27 05:06 UTC, kchibisov approved these changes

2023-01-27 06:02 UTC, merged

2023-03-26 20:46 UTC, utkarshgupta137 commented
On macOS, most apps use `Cmd + T` to open a new tab in the same window (CreateNewWindow) & `Cmd + N` to open a new separate window (SpawnNewInstance). Any reason why `Cmd + N` was changed instead of using `Cmd + T` like most other mac apps?

2023-03-26 21:57 UTC, utkarshgupta137 commented
> On macOS, most apps use `Cmd + T` to open a new tab in the same window (CreateNewWindow) & `Cmd + N` to open a new separate window (SpawnNewInstance). Any reason why `Cmd + N` was changed instead of using `Cmd + T` like most other mac apps?

Please ignore my comment, it looks like `CreateNewWindow` is creating a new tab due to this setting in mac:

<img width="473" alt="image" src="https://user-images.githubusercontent.com/5155100/227807104-ccd215a5-65a7-4bb4-b6df-06b111481606.png">

So I guess it makes sense to keep `Cmd + N` for people who've not changed that setting.

2023-04-20 06:24 UTC, axieax commented
Is there a particular reason why the default isn't `Cmd + T` for creating a new tab (`CreateNewWindow`) and `Cmd + N` for creating a new window (`SpawnNewInstance`), as would be expected for any MacOS shortcut? Happy to make a PR to address this change.

2023-04-20 07:49 UTC, chrisduerr commented
There's no difference between creating a new tab or window in Alacritty. It just depends on your system configuration.