feat: update default macOS new window bindings
alacritty/alacritty pull request #6876
Opened 2023-04-20 06:36 UTC by axieax

This PR addresses the unconventional bindings introduced by #6648, adding the following macOS bindings:

- `Cmd + T` for `CreateNewWindow` (mimics opening a new tab if system-enabled)
- `Cmd + N` for `SpawnNewInstance` (opens a separate Alacritty window)

2023-04-20 07:40 UTC, utkarshgupta137 commented
This is the behavior I expect since I've changed the following setting:
![image](https://user-images.githubusercontent.com/5155100/233294977-dfceb551-ef4c-4564-82d0-dab86ae007de.png)

With these keybindings, Cmd+T opens a new tab & Cmd+N opens a new window like every other macOS app.
I don't think changing these bindings will affect people who've not changed the above setting.

2023-04-20 07:50 UTC, chrisduerr requested changes
`CreateNewWindow` can open a new window just like `SpawnNewInstance` does.

2023-04-20 07:50 UTC, closed without merging

2023-04-20 07:52 UTC, utkarshgupta137 commented
> `CreateNewWindow` can open a new window just like `SpawnNewInstance` does.

If we change the above-mentioned setting in macOS, `CreateNewWindow` opens a new OS tab whereas `SpawnNewInstance` opens a new OS window. So there is a difference.

2023-04-20 09:15 UTC, kchibisov commented
Be aware that `SpawnNewInstance` is not something macOS applications do at all.

2023-04-20 16:29 UTC, chrisduerr commented
> If we change the above-mentioned setting in macOS, CreateNewWindow opens a new OS tab whereas SpawnNewInstance opens a new OS window. So there is a difference.

Pretending that's the difference between the two actions is just a gross misrepresentation of what they do.

2023-04-21 03:53 UTC, axieax commented
Is there a way to specifically open a new MacOS tab for new windows (perhaps as a window option)?

2023-04-21 04:59 UTC, chrisduerr commented
> Is there a way to specifically open a new MacOS tab for new windows (perhaps as a window option)?

There is not, which is why there is no such binding in Alacritty by default.

2023-04-21 05:29 UTC, utkarshgupta137 commented
@axieax Are you talking about something like this:
<img width="1800" alt="image" src="https://user-images.githubusercontent.com/5155100/233547583-e26a190c-3349-41db-aebd-cff94ee59fda.png">

If so, change the following setting in system preferences:
![image](https://user-images.githubusercontent.com/5155100/233547679-a55c7304-808a-475e-8b41-1df8145fcc06.png)

Then bind `Cmd + T` to `CreateNewWindow` (& maybe `Cmd + N` to `SpawnNewInstance` to open a separate macOS window). See alacritty.yml in this PR. 

Bonus tip: You can use `Cmd + Shift + [ / ]` to go to the left or right tab. (This shortcut works for most macOS apps)

2023-04-22 12:02 UTC, axieax commented
@utkarshgupta137 yep that's the tab view I'm referring to, and it would be nice for there to be a way to specifically target whether to open a "tab" or a "window" without having to change the global system settings just for this one application.

2023-04-22 12:06 UTC, utkarshgupta137 commented
> @utkarshgupta137 yep that's the tab view I'm referring to, and it would be nice for there to be a way to specifically target whether to open a "tab" or a "window" without having to change the global system settings just for this one application.

The "tabs" you're seeing in alacritty is a feature of the macOS's window manager. Alacritty itself doesn't support tabs. I'm not sure if macOS supports changing this on a per-app basis. I think this should work: https://apple.stackexchange.com/a/458847/387376

2023-04-23 21:06 UTC, axieax commented
Got this to work now, thanks for all the help @utkarshgupta137!! 🎉🎉