Ignore scrolling multiplier when using touchscreen
alacritty/alacritty pull request #7034
Opened 2023-06-26 17:43 UTC by 4z3

This causes the scrolling multiplier to be ignored when scrolling using the touchscreen. Without this change, scrolling is out of sync with the position of the finger on the touchscreen.

2023-06-26 22:25 UTC, chrisduerr requested changes
Why not just set the scroll multiplier to 1 in your config?

2023-07-04 01:51 UTC, chrisduerr commented
I didn't get around to testing it this weekend, so it'll have to wait a couple more days. Just wanted to let you know that it might take till the end of the week until I get around to it.

2023-07-16 21:17 UTC, chrisduerr commented
It looks like I won't be able to get around to this today either, so I'm not giving any further ETAs. But since this does affect me on my phone, I will definitely keep track of it and look into it as soon as my compositor is working properly again.

2023-08-05 18:27 UTC, chrisduerr approved these changes
Sorry for the massive delay, I finally got around to testing this on my phone and it is an absolutely massive improvement.

Thanks for the patch.

2023-08-05 18:32 UTC, kchibisov commented on alacritty/src/input.rs
> +                self.scroll_terminal(0., delta_y, 1.0);
Could we have extra comment why it's done that way, so it won't get removed by accident?

2023-08-05 19:08 UTC, merged