Update mentions of key_bindings and mouse_bindings in the manual
alacritty/alacritty pull request #7055
Opened 2023-07-05 18:10 UTC by proski

2023-07-05 21:36 UTC, kchibisov requested changes

2023-07-05 21:36 UTC, kchibisov commented on extra/man/alacritty.5.scd
> +	*action* <keyboard_bindings_action> | "ExpandSelection"
```suggestion
	*action* <keyboard.bindings_action> | "ExpandSelection"
```

2023-07-05 22:26 UTC, kchibisov approved these changes

2023-07-05 23:06 UTC, chrisduerr requested changes
I think we should document keyboard/mouse as separate sections for the sake of consistency.

2023-07-05 23:46 UTC, proski commented
@chrisduerr Please explain. The documentation is already using separate sections. The only overlap is in the actions. I can move actions to a separate section.

2023-07-06 23:00 UTC, chrisduerr commented
`keyboard` and `mouse` are TOML tables and should be in dedicated sections. No other section is collapsed the way you did it.

2023-07-07 02:37 UTC, kchibisov commented
@proski if it's not clear what is wanted here, the mouse and bindings sections are both in the `# Bindings`, however what was suggested instead is that `mouse_bindings` will be moved to `# Mouse` section and will be called not `mouse.bindings`, but just `bindings`.

The same for keyboard, however the `# Bindings` should be renamed to `# Keyboard` at this point and `key_bindings` will become just `bindings`.

That should be just moving sections around.

The `# Keyboard` section should have entry docs like `# Mouse` one.

2023-07-07 20:33 UTC, proski commented
The manual sections reflect the top-level sections of the TOML file now.

2023-07-07 21:01 UTC, kchibisov approved these changes

2023-07-07 21:36 UTC, chrisduerr approved these changes

2023-07-07 21:37 UTC, merged