Update winit to 0.29.1
alacritty/alacritty pull request #7220
Opened 2023-09-16 10:41 UTC by kchibisov

Fixes #7201.

2023-09-22 16:51 UTC, sukima commented
I would like to confirm, after applying this patch that…

* My slow refreshes while coding in Vim are **gone**
* My TMUX is responding way **faster**
* My Emojis are crystal clear now
* My fonts are much bigger (my eyes thank you)
* Everything runs so much faster and snappier

Thank you!!!!

2023-09-22 16:56 UTC, kchibisov commented
@sukima I'm not sure why you have so many things fixed if this PR literally changed nothing compared to them. Probably an oversight.

2023-09-22 16:58 UTC, sukima commented
It is possible that a `git pull` also contributed to several fixes. But this PR defiantly fixed the #7201 problem I've been having.

2023-09-26 22:34 UTC, proski commented
This PR solves major issues with MacOS 14 Sonoma that was released today. Alacritty 0.12.2 doesn't work at all, it hangs. The current master branch makes the first line of text appear partially behind the title. Selecting text with the mouse selects on the line above the expected one. Alacritty build from this PR is working properly for me.

Not sure if we need a bug to track Sonoma issues, but I believe a new release is needed very soon.

2023-09-26 22:38 UTC, kchibisov commented
did mac broke things **so** badly? We have the same macOS code for 4 years, I'm pretty sure we're not the only one affected by that.

2023-09-27 16:50 UTC, proski commented
Everything else appears to be working correctly, including the standard Terminal app. I've opened a ticket #7242 specifically for that issue.

2023-09-27 20:15 UTC, kchibisov commented
Hm, I think it's because Apple changed the way resizes work and the way viewport sizes are being reported, and given that winit used different thing it sort of broke stuff.

Out of curiousity, could check with `--print-events` resizes on the `0.12.2`? Maybe that's this issue https://github.com/rust-windowing/winit/issues/2876 ? 

I question, because maybe we should really back port and do a patch release of the winit itself, and maybe even alacritty?

2023-09-27 20:30 UTC, proski commented
I'm sure it's that issue.
```
[0.000274625s] [INFO ] [alacritty] Welcome to Alacritty
[0.000515667s] [INFO ] [alacritty] Version 0.12.2 (9d9982df)
[0.001379125s] [INFO ] [alacritty_config_derive] No config file found; using default
[0.016426167s] [INFO ] [alacritty] winit event: NewEvents(Init)
[0.016482667s] [INFO ] [alacritty] winit event: Resumed
[0.016543250s] [INFO ] [alacritty] Using Apple CGL
[0.042976333s] [INFO ] [alacritty] Window scale factor: 2
[0.071208917s] [INFO ] [alacritty] Running on Apple M2 Max
[0.071232042s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.082526708s] [INFO ] [alacritty] Cell size: 13 x 25
[0.082547708s] [INFO ] [alacritty] Padding: 0 x 0
[0.082559708s] [INFO ] [alacritty] Width: 1600, Height: 1200
[0.086401458s] [INFO ] [alacritty] PTY dimensions: 48 x 123
[0.088278708s] [INFO ] [alacritty] Initialisation complete
[0.092647333s] [INFO ] [alacritty] winit event: RedrawRequested(WindowId(WindowId(5636403584)))
[0.095163458s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5636403584)), event: Resized(PhysicalSize { width: 4294967295, height: 4294967295 }) }
[0.095196583s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5636403584)), event: Focused(false) }
[0.095216458s] [INFO ] [alacritty] winit event: MainEventsCleared
[0.095234250s] [INFO ] [alacritty] winit event: RedrawRequested(WindowId(WindowId(5636403584)))
[0.095249292s] [INFO ] [alacritty] winit event: RedrawEventsCleared
thread 'PTY reader' panicked at alacritty_terminal/src/tty/unix.rs:418:25:
attempt to multiply with overflow
```

2023-09-27 21:05 UTC, kchibisov commented
Thanks, I'll try to see whether we can backport that, but maybe not into alacritty itself.

At least the rest of the ecosystem could have the fix without waiting on the update of winit.

2023-09-27 21:12 UTC, proski commented
I reverted https://github.com/rust-windowing/winit/issues/2876 on a local copy of winit and used it with the code from this PR. It triggered **both** issues I reported in #7242, the overflow panic in the Windowed mode and the lines behind the title in the Maximized mode. So apparently the backport would be very useful, considering that users are updating to MacOS 14 en masse after the release.

2023-10-12 23:40 UTC, proski commented
Please don't forget to update copypasta version in the commit title.

2023-10-20 16:24 UTC, tbozan commented
With this last version of pr only upper left quarter of a terminal window is clickable (beam cursor, can select text, instead of regular cursor and unable to select text in other three quarters).
As i'm using 2x scaling i'm guessing there's a chance that it has something to do with hidpi.
Last working version of this pr was 67382eb.

2023-10-20 16:35 UTC, kchibisov commented
@tbozan could you be more specific on that matter?

2023-10-20 16:41 UTC, tbozan commented
Sorry about that. Latest mesa and linux kernel, picom compositor.
Basically when i'm interacting with the mouse (clicking, selecting text...) with upper left quarter of the window everything works as expected. When interacting with other three quarters nothing happens, like i'm clicking on a screenshot of a window.

2023-10-20 16:43 UTC, kchibisov commented
@tbozan could you provide the `--print-events` log and the log when you click on different parts of the window?

2023-10-20 16:58 UTC, tbozan commented
When moving the cursor or clicking on upper left quarter i'm getting the usual events:
```
[2.855835398s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 18595, tv_nsec: 743574320 }, requested_resume: Some(Instant { tv_sec: 18596, tv_nsec: 132330815 }) })
[2.855840097s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(25165827)), event: CursorMoved { device_id: DeviceId(X(DeviceId(2))), position: PhysicalPosition { x: 780.0, y: 292.0 } } }
[2.855844487s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(25165827)), event: AxisMotion { device_id: DeviceId(X(DeviceId(2))), axis: 0, value: 782.0 } }
[2.855849327s] [INFO ] [alacritty] winit event: AboutToWait
[2.856835703s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 18595, tv_nsec: 744574296 }, requested_resume: Some(Instant { tv_sec: 18596, tv_nsec: 132330815 }) })
[2.856840923s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(25165827)), event: CursorMoved { device_id: DeviceId(X(DeviceId(2))), position: PhysicalPosition { x: 784.0, y: 292.0 } } }
[2.856845193s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(25165827)), event: AxisMotion { device_id: DeviceId(X(DeviceId(2))), axis: 0, value: 786.0 } }
[2.856849963s] [INFO ] [alacritty] winit event: AboutToWait
[2.857835939s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 18595, tv_nsec: 745519402 }, requested_resume: Some(Instant { tv_sec: 18596, tv_nsec: 132330815 }) })
[2.857842199s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(25165827)), event: CursorMoved { device_id: DeviceId(X(DeviceId(2))), position: PhysicalPosition { x: 791.0, y: 293.0 } } }
[2.857849399s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(25165827)), event: AxisMotion { device_id: DeviceId(X(DeviceId(2))), axis: 0, value: 793.0 } }
[2.857853569s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(25165827)), event: AxisMotion { device_id: DeviceId(X(DeviceId(2))), axis: 1, value: 371.0 } }
[2.857858689s] [INFO ] [alacritty] winit event: AboutToWait
[2.858838005s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 18595, tv_nsec: 746585238 }, requested_resume: Some(Instant { tv_sec: 18596, tv_nsec: 132330815 }) })
[2.858843235s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(25165827)), event: CursorMoved { device_id: DeviceId(X(DeviceId(2))), position: PhysicalPosition { x: 795.0, y: 293.0 } } }
[2.858847995s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(25165827)), event: AxisMotion { device_id: DeviceId(X(DeviceId(2))), axis: 0, value: 797.0 } }
[2.858853195s] [INFO ] [alacritty] winit event: AboutToWait
[2.859838050s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 18595, tv_nsec: 747585753 }, requested_resume: Some(Instant { tv_sec: 18596, tv_nsec: 132330815 }) })
[2.859844100s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(25165827)), event: CursorMoved { device_id: DeviceId(X(DeviceId(2))), position: PhysicalPosition { x: 799.0, y: 293.0 } } }
[2.859848860s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(25165827)), event: AxisMotion { device_id: DeviceId(X(DeviceId(2))), axis: 0, value: 801.0 } }
[2.859854170s] [INFO ] [alacritty] winit event: AboutToWait
[2.860839336s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 18595, tv_nsec: 748579459 }, requested_resume: Some(Instant { tv_sec: 18596, tv_nsec: 132330815 }) })
[2.860844486s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(25165827)), event: CursorLeft { device_id: DeviceId(X(DeviceId(2))) } }
[2.860849576s] [INFO ] [alacritty] winit event: AboutToWait
[3.243674390s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 18595, tv_nsec: 749519005 }, requested_resume: Instant { tv_sec: 18596, tv_nsec: 132330815 } })
[3.243689990s] [INFO ] [alacritty] winit event: AboutToWait
[3.243698980s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 18596, tv_nsec: 132362189 }, requested_resume: Some(Instant { tv_sec: 18596, tv_nsec: 757360509 }) })
[3.243704300s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(25165827))), payload: BlinkCursor })
[3.243709420s] [INFO ] [alacritty] winit event: AboutToWait
[3.243714580s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 18596, tv_nsec: 132378899 }, requested_resume: Some(Instant { tv_sec: 18596, tv_nsec: 757360509 }) })
[3.243720290s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(25165827)), event: RedrawRequested }
[3.244190609s] [INFO ] [alacritty] winit event: AboutToWait
[3.244201948s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 18596, tv_nsec: 132864457 }, requested_resume: Some(Instant { tv_sec: 18596, tv_nsec: 757360509 }) })
[3.244207888s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(25165827))), payload: Frame { force: false } })
```

With other three quarters nothing happens when moving the cursor, only when i click on the window i get:
```
[3.314887544s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 18596, tv_nsec: 132881467 }, requested_resume: Some(Instant { tv_sec: 18596, tv_nsec: 757360509 }) })
[3.314906624s] [INFO ] [alacritty] winit event: AboutToWait
[3.398846904s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 18596, tv_nsec: 203576913 }, requested_resume: Some(Instant { tv_sec: 18596, tv_nsec: 757360509 }) })
[3.398871134s] [INFO ] [alacritty] winit event: AboutToWait
[3.668881109s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 18596, tv_nsec: 287541613 }, requested_resume: Some(Instant { tv_sec: 18596, tv_nsec: 757360509 }) })
[3.668898769s] [INFO ] [alacritty] winit event: AboutToWait
[3.752828639s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 18596, tv_nsec: 557568778 }, requested_resume: Some(Instant { tv_sec: 18596, tv_nsec: 757360509 }) })
[3.752840928s] [INFO ] [alacritty] winit event: AboutToWait
[3.868705206s] [INFO ] [alacritty] winit event: NewEvents(ResumeTimeReached { start: Instant { tv_sec: 18596, tv_nsec: 641510797 }, requested_resume: Instant { tv_sec: 18596, tv_nsec: 757360509 } })
[3.868721536s] [INFO ] [alacritty] winit event: AboutToWait
```
One pair of `NewEvents(WaitCancelled...` and `AboutToWait` for click-down and click-up.

2023-10-20 17:05 UTC, kchibisov commented
Could you also paste the log `alacritty -vv --print-events` without actually truncating it?

2023-10-20 17:11 UTC, tbozan commented
Here it is: https://gist.github.com/tbozan/9fbe3cb28596d139bca0d6ad86b8c3ea

2023-10-20 17:15 UTC, kchibisov commented
Does it happen with `alacritty --config-file /dev/null`?

2023-10-20 17:21 UTC, tbozan commented
Good catch. When i comment out window.dimensions and restart alacritty everything works, even when i manually resize window.

2023-10-21 07:50 UTC, kchibisov commented
@tbozan your issue should be fixed now. Thanks.

2023-10-21 18:01 UTC, chrisduerr requested changes

2023-10-21 18:01 UTC, chrisduerr commented on alacritty/src/event.rs
> +                            drop(windows);
Doesn't just `self.windows.clear()` have the same effect?

2023-10-21 18:01 UTC, chrisduerr commented on alacritty/src/event.rs
> +                            // EGL state will be made.
Formatting.

2023-10-21 18:15 UTC, kchibisov commented on alacritty/Cargo.toml
> +winit = { version = "0.29.2", default-features = false, features = ["rwh_05", "serde"] }
yes. probably, but we have a lot of them and you need multiple at the same time, so you won't have a giant name. You'd also have to alias `raw-window-handle` to something in your code if you use multiple handles, they are not mutually exclusive, but rather additive.

2023-10-21 18:54 UTC, chrisduerr approved these changes

2023-10-21 18:56 UTC, merged

2024-01-24 19:56 UTC, ProNoob135 commented
After this commit, Alacritty hangs if moved off my primary monitor.
`./target/debug/alacritty -vv --print-events --config-file /dev/null`
[Alacritty-3416.log](https://github.com/alacritty/alacritty/files/14042765/Alacritty-3416.log)
Here's how far it gets if launched on my other monitors:
[Alacritty-4406.log](https://github.com/alacritty/alacritty/files/14042830/Alacritty-4406.log)
I'm assuming something is off with my system configuration, but I've no idea what.
XFCE4(X11), three monitors, here's my xorg.conf:
```Section	"Monitor"
	Identifier	"HDMI-A-0"
	Option	"Position"	"0 180"
EndSection

Section	"Monitor"
	Identifier	"DisplayPort-1"
	Modeline	"2560x1440_143.97"  592.25  2560 2581 2613 2666  1440 1443 1448 1543 +hsync -vsync
	Option	"PreferredMode"	"2560x1440_143.97"
	Option	"Position"	"1920 0"
	Option	"Primary"	"true"
EndSection

Section "Monitor"
	Identifier	"DisplayPort-2"
	Option	"PreferredMode"	"1920x1080"
	Option	"Position"	"4480 360"
	Option	"DPMS"	"false"
EndSection```