Allow and prefer exact matches for bindings in mouse mode
alacritty/alacritty pull request #7300
Opened 2023-10-17 23:44 UTC by proski

Only consider bindings without Shift if there are no actions defined for the actual mouse event.

2023-10-18 00:08 UTC, proski commented
The implementation follows the suggestion I've got in #7292. The actions defined for the actual mouse event (with Shift modifier if Shift is actually pressed) take priority. The actions for the bindings with Shift removed are only considered is there are no actions for the actual event.

I tried to make implementation as simple as the original. `clone()` is only called on the actions that match the event, not on every binding. The `binding` variable is immutable now. It iterates over the bindings naturally, without access by index. The modification is made to the actual event modifiers, not to the bindings, which makes the logic more transparent (Shift is removed from the event, not added to the binding).

Once there is any exact match, fallback matches are not populated anymore.

2023-10-18 17:58 UTC, proski commented
The code is working well for me, I'm using it as my normal terminal. Both middle-click and Shift-middle-click are pasting exactly once everywhere. I had to disable paste on middle-click in vim to prevent double paste without Shift. All other mouse operations are working as expected.

An alternative approach is to put actions to a set, which would remove duplicate actions. That would require hash support on actions and some other types. I don't think anyone would want one action to run multiple times for an event. However, `Paste` and `PasteSelection` are different events, so some users can end up with both being emitted for one event.

2023-10-19 14:40 UTC, kchibisov commented on alacritty/src/input.rs
> +            action.execute(&mut self.ctx);
Could you simply take the code which was there before and do 2 loops? The amount of bindings is very low so it's better than `vec` approach.

Just do normal loop without `mouse_mode` part and set some flag to `true` when you actually triggered some binding.

And then, `if mouse_mode && !sent_binding` do the ho the same loop, but with `SHIFT` applied? First loop won't need to `clone` even, I think.

2023-10-19 21:57 UTC, proski commented
I've implemented 2 loops as you requested. Unfortunately, I have to use the same iteration by index and cloning in both loops, and I cannot find a way to avoid it without executing actions outside the loops, which would need a vector or some other data structure.

2023-10-20 00:02 UTC, proski commented
I was able to get rid of indices and `clone()` by using `to_owned()` for `mouse_bindings`. That just one memory allocation per function call, as opposed to allocations for every binding on `clone()`.

2023-10-20 02:53 UTC, chrisduerr requested changes
Missing a changelog entry.

2023-10-20 02:53 UTC, chrisduerr commented on alacritty/src/input.rs
> +        let mut fallback_needed = mouse_mode && mods.contains(ModifiersState::SHIFT);
```suggestion
        let mut check_fallback = mouse_mode && mods.contains(ModifiersState::SHIFT);
```

2023-10-20 02:53 UTC, chrisduerr commented on alacritty/src/input.rs
>                  binding.action.execute(&mut self.ctx);
```suggestion
                binding.action.execute(&mut self.ctx);
                fallback_needed = false;
```

2023-10-21 00:08 UTC, proski commented
Addressed the comments.

2023-10-21 01:49 UTC, chrisduerr commented
If you want another review, please request it.

2023-10-21 04:57 UTC, kchibisov approved these changes

2023-10-21 18:10 UTC, chrisduerr requested changes

2023-10-21 18:10 UTC, chrisduerr commented on alacritty/src/input.rs
> +        // If mouse mode is active, also look for bindings without Shift
```suggestion
        // If mouse mode is active, also look for bindings without shift.
```

2023-10-22 17:45 UTC, proski commented on alacritty/src/input.rs
> +        // If mouse mode is active, also look for bindings without Shift
Done

2023-10-24 23:35 UTC, chrisduerr approved these changes
Thanks for the PR.

2023-10-25 00:04 UTC, merged