Make AA stronger for undercurl
alacritty/alacritty pull request #7394
Opened 2023-11-24 18:04 UTC by kchibisov

This improves undercurl rendering preserving its original thickness. This also makes it look not out-of place when places next to other lines.

--

Before

![image](https://github.com/alacritty/alacritty/assets/27620401/7898007a-eb08-499e-9962-b54af321533d)

After

![image](https://github.com/alacritty/alacritty/assets/27620401/11467e0c-c1c1-429d-aa49-d799773fbaf2)

2023-11-24 18:52 UTC, chrisduerr requested changes

2023-11-24 18:52 UTC, chrisduerr commented on alacritty/res/rect.f.glsl
> +    // being bold enough.
```suggestion
    // Doing proper SDF is complicated for this shader, so just make AA
    // stronger by 1/x^2, which renders preserving underline thickness and
    // being bold enough.
```

2023-11-24 19:54 UTC, chrisduerr approved these changes

2023-11-24 19:57 UTC, merged

2023-11-29 13:36 UTC, nixpulvis commented
Am I crazy, or should the undercurl be about 1px or so higher now?

2023-11-29 13:42 UTC, kchibisov commented
it's the same as underline in terms of thickness, I just made it brighter.