Added the ability to paste in search mode
alacritty/alacritty pull request #7528
Opened 2024-01-01 23:40 UTC by omagdy7

Fixes #7511

2024-01-01 23:51 UTC, kchibisov requested changes
This is not right way to solve this, since now you paste `twice` into normal search prompt.

Probably the solution would be for each paste binding and a paste binding in `vi | search` mode.

2024-01-01 23:59 UTC, omagdy7 commented
> This is not right way to solve this, since now you paste `twice` into normal search prompt.

When I tested the change only one paste happens when I press "CTRL+SHIFT+V", Or are you referring to something else?

![demo](https://github.com/alacritty/alacritty/assets/99906646/6569f3e7-6060-4e53-8cee-a7562a1b841b)

2024-01-02 00:04 UTC, omagdy7 commented
Ok I think I got it normal search mode without vi gets triggered twice oh my bad

2024-01-02 00:47 UTC, chrisduerr requested changes
Missing a changelog entry.

2024-01-02 11:14 UTC, kchibisov requested changes

2024-01-02 11:14 UTC, kchibisov commented on alacritty/src/config/bindings.rs
> +        "v",    ModifiersState::CONTROL | ModifiersState::SHIFT, +BindingMode::VI, +BindingMode::SEARCH; Action::Paste;
You should do the same for all other bindings `Paste` bindings, as well as document them in the `alacritty-binding.5.scd` man page.

2024-01-02 14:00 UTC, omagdy7 commented
The alacritty-bindings man syntax was really confusing I hope I got it right but what kind of format is that? I've never seen it before

2024-01-02 14:24 UTC, chrisduerr requested changes

2024-01-02 14:24 UTC, chrisduerr commented on CHANGELOG.md
> +- Support for pasting in Vi + Search mode
Please check the correct section order at the top of the file.

2024-01-02 14:51 UTC, chrisduerr requested changes

2024-01-04 13:00 UTC, chrisduerr requested changes

2024-01-04 13:00 UTC, chrisduerr commented on extra/man/alacritty-bindings.5.scd
>  :  _"Paste"_
This old binding doesn't actually show the mode as `~Vi`, could you fix that?

2024-01-04 17:03 UTC, chrisduerr approved these changes
Thank you for the PR.

2024-01-04 17:57 UTC, merged