Add config file locations into config manpage
alacritty/alacritty pull request #7938
Opened 2024-04-29 10:13 UTC by akx

I was trying to look for this information in https://alacritty.org/config-alacritty.html, but it wasn't there! Had to spelunk around a bit to find it in the readme instead...

2024-04-30 16:24 UTC, nixpulvis commented
Might also be a good idea to mention #7690 if/when that lands. Not that that should block this PR, just something that came to my mind.

2024-04-30 18:36 UTC, chrisduerr requested changes

2024-04-30 18:36 UTC, chrisduerr commented on extra/man/alacritty.5.scd
> +On Windows, the config file should be located at:
We should reuse the "looks for"/search verbs here. There shouldn't be a config file there, it's all optional.

2024-05-03 09:16 UTC, chrisduerr approved these changes

2024-05-03 17:44 UTC, merged