Add `from_file_descriptors` to `tty::unix`
alacritty/alacritty pull request #7940
Opened 2024-04-30 18:58 UTC by someone13574

Adds a function to create a `Pty` handle from file descriptors opened outside of Alacritty. This does not break backward compatibility.

2024-04-30 19:05 UTC, nixpulvis reviewed
Is there a reason for this change? A use case for a consumer application?

2024-04-30 19:05 UTC, nixpulvis commented on alacritty/Cargo.toml
> -version = "0.23.0-dev"
Probably shouldn't be touched here.

2024-04-30 19:30 UTC, someone13574 commented
> Is there a reason for this change? A use case for a consumer application?

I'm working on flatpak support for [Zed](https://github.com/zed-industries/zed), which uses `alacritty_terminal` for it's builtin terminal, but in order to properly spawn the shell process on the host system one needs to pass the file descriptors of the command been spawned to the `--forward-fd` argument [flatpak-spawn](https://man7.org/linux/man-pages/man1/flatpak-spawn.1.html). This doesn't work however as alacritty doesn't expose the file descriptors until we have already passed the shell command to use, thus the need open the PTY ourselves so the fd's are available.

2024-04-30 21:28 UTC, chrisduerr requested changes
Seems simple enough and the stuff you have to do outside is also trivial (`openpty`).

So this solution makes more sense than basically exposing a function that is the same as `openpty` just with some `spawn` call attached.

2024-04-30 21:28 UTC, chrisduerr commented on alacritty_terminal/src/tty/unix.rs
> +pub fn from_file_descriptors(
I think `fd` is actually more universally used than `file_descriptor`.

```suggestion
pub fn from_fd(
```

2024-04-30 21:28 UTC, chrisduerr commented on alacritty_terminal/src/tty/unix.rs
> +/// Create a new TTY from a Pty's file descriptors.
I'm a bit bothered by TTY being all capitals, but Pty being camel case. I'd just upper them all.

2024-04-30 22:24 UTC, nixpulvis approved these changes
😄

Just letting @chrisduerr make the final review.

2024-05-01 04:53 UTC, chrisduerr requested changes
Another tiny nitpick. Doubt I can find anything else.

2024-05-01 04:53 UTC, chrisduerr commented on alacritty_terminal/CHANGELOG.md
> +- Added `tty::unix::from_fd()` to create a TTY from a pre-opened PTY's file-descriptors
```suggestion
- `tty::unix::from_fd()` to create a TTY from a pre-opened PTY's file-descriptors
```

If we add `Added` to every entry in the Added section, we're not really gaining anything.

2024-05-01 05:27 UTC, chrisduerr approved these changes

2024-05-01 05:27 UTC, merged

2024-05-01 05:29 UTC, someone13574 commented
> @someone13574 Do you need this released?

Yes, that would be awesome.

2024-05-01 06:59 UTC, chrisduerr commented
No promises on the ETA, but I'll try and get a release out this week.