Expose the command execution interface using ExecArg
alacritty/alacritty pull request #8139
Opened 2024-08-21 17:53 UTC by ManuelSchneid3r

According to the upcoming xdg-terminal-exec specification. 

This is the only change needed to support the spec. No fancy dbus or such.

2024-08-21 19:28 UTC, chrisduerr requested changes
> According to the upcoming xdg-terminal-exec specification.

If the proposal hasn't even been accepted, why would we implement it?

2024-08-21 21:38 UTC, ManuelSchneid3r commented
It has not been rejected either. It's a draft. It's not unusual that drafts are used as if they were approved. Eg icon naming spec. It's a minimal change that makes sense in my eyes.
Actually I don't like the proposal as it is atm. But it's implications on the desktop entry spec totally make sense. I have seen several terminal breaking this interface (arg changed). If the package does not tell how, it is impossible to interface it reliably.

2024-08-22 00:54 UTC, chrisduerr commented
> Actually I don't like the proposal as it is atm.

Which is exactly why it doesn't make sense to just implement random proposals.

2024-08-22 00:54 UTC, closed without merging

2024-08-22 08:40 UTC, ManuelSchneid3r commented
Don't get me wrong. I support the idea of having a standardized desktop entry interface. What I dont like is having a default of -e. The idea is still great and there is no other way of exposing the interface reliably than exposing it in the desktop entry.

2024-08-22 09:58 UTC, kchibisov commented
The main problem is that the spec is not _accepted_, it's not like there's something wrong with it from what I can tell.

And adding support for _unaccepted_ is not a great idea, especially given it can change at any time or not be implemented in any DE at all.

2024-08-22 13:49 UTC, chrisduerr commented
I'd be fine with this if it was accepted, yes. But it not only seems to be unaccepted, it also seems to be highly disputed with competing proposals present.

2024-08-22 21:03 UTC, ManuelSchneid3r commented
Well yes due to the terminal intent which will probably never get off the ground and even if so it will never be supported by all terminals.

Imho it's not even competing. They overlap. Xte is limited in features but can be supported by virtually every temrinal out there, terminal intent has more features yet and is even extensible but will never be implemented by all terminals.

For the sake of UX my suggestion is to let clients implement them both.

2024-08-22 21:16 UTC, kchibisov commented
The problem is that they are not _accepted_, as in they can change any other day, so when you ask to implement Xte, it means that you ask to implement what is _available_ at the time of writing all of that.

Tomorrow, it could all change, because it's not _accepted_. As we said, upstream should _accept_ the spec first and then we'll implement it, that's how it _works_.

Keeping PR as an indication of _intent_ is good to show that e.g. downstream is interested, but we can not merge anything unless it's _accepted_.

The same goes for the other protocol, since it's not accepted _either_.

2025-09-19 14:46 UTC, djsigmann commented
I'd like to make the case for either reopening this PR or allowing a new one to be opened, since I believe this would be a fairly useful feature with no drawbacks that only requires a couple lines in a desktop entry file to be added.

My argument for implementing this in alacritty is that [kitty has already done so in march](https://github.com/kovidgoyal/kitty/pull/8410).

2025-09-19 17:40 UTC, ManuelSchneid3r commented
As an aside lots of xdg specs are still draft yet implemented everywhere. Seriously it's a minor change in the desktop entry without any side effects.

2025-09-26 13:39 UTC, ManuelSchneid3r commented
Jfyi, check the icon-naming-spec,  the icon-theme-spec and _especially_ the *xdg base dir spec*. All drafts.

Linux desktop develops from bottom up not top down.

2025-12-29 11:14 UTC, ManuelSchneid3r commented
Do you mind reconsidering this?

2025-12-29 12:49 UTC, chrisduerr commented
> Do you mind reconsidering this?

Why would I? Has anything changed regarding the concerns I've expressed previously?

2025-12-29 12:59 UTC, ManuelSchneid3r commented
Well maybe, after I argued that even specs like base dir spec are still drafts today, your position on implementing non approved specs.

2025-12-29 16:37 UTC, chrisduerr commented
> Well maybe, after I argued that even specs like base dir spec are still drafts today, your position on implementing non approved specs.

Those are all specs that are publicly hosted on specifications.freedesktop.org, which expresses at least a bare minimum of support for it. The ExecArg "spec" didn't even manage to get that far.

2025-12-29 17:51 UTC, ManuelSchneid3r commented
If you talked to the people and saw how things work there you'd not be surprised. _Gnome terminal_, which is the most popular Linux terminal by a multitude, "implemented" it (its still just one line of metadata) . I'd argue the proposal actually got quite far.

2025-12-30 00:29 UTC, chrisduerr commented
> Gnome terminal, which is the most popular Linux terminal by a multitude, "implemented" it (its still just one line of metadata).

Gnome just implements whatever they want without any care for standards, so this means nothing.

> I'd argue the proposal actually got quite far.

Some terminals just implemented it because it's easy. As far as the actual proposal goes, it went absolutely nowhere.