Allow Alacritty to be run as a "background" app
alacritty/alacritty pull request #8167
Opened 2024-09-11 11:52 UTC by purajit

2024-09-12 01:12 UTC, chrisduerr requested changes
What's the point of this feature?

2024-09-12 01:47 UTC, purajit commented
> What's the point of this feature?

The main way people use it is to have a terminal that can be summoned from anywhere, while not interfering with the window switcher. The first part is achieved with OS automation and should not be part of Alacritty, as I've seen you argue before and agree with, but the second is a flag that's set when creating the window.

The idea is basically: since Alacritty can be summoned from anywhere, there's no reason for it to show up the in the window switcher and prevent you from having your actual previous window accessible with an immediate Cmd-Tab.

Considering that it's part of the window manager, it's a flag available in winit and the OS that's locked away right now.

2024-09-12 02:01 UTC, purajit commented
> > The idea is basically: since Alacritty can be summoned from anywhere, there's no reason for it to show up the in the window switcher and prevent you from having your actual previous window accessible with an immediate Cmd-Tab.
> 
> Why? The whole point of the window switcher is to show your windows, is it not?

The idea of `ActivationPolicy.accessory` (doc linked in PR) is that applications and windows can be separate - so an application may be running, but not have a window, until programmatically triggered. ([Spotlight](https://en.wikipedia.org/wiki/Spotlight_(Apple)), the built-in application launcher is a good example - you programmatically trigger it with Cmd-Space, but otherwise it doesn't actually have a window.

2024-09-12 02:36 UTC, chrisduerr commented
A terminal shouldn't just be running in the background and have one window that pops up though. Does this not show up in the bar at the bottom at all then? Is there only one global window, or does it spawn multiple?

I'd say if it doesn't show up in the bottom panel like all other applications, then I'm not sure this is appropriate for Alacritty. At that point its behavior would seem a bit sketchy to me?

2024-09-12 02:45 UTC, purajit commented
> A terminal shouldn't just be running in the background and have one window that pops up though. Does this not show up in the bar at the bottom at all then? Is there only one global window, or does it spawn multiple?
> 
> I'd say if it doesn't show up in the bottom panel like all other applications, then I'm not sure this is appropriate for Alacritty. At that point its behavior would seem a bit sketchy to me?

One window vs multiple just depends on how you program it - I have it as a single global window; based on a shortcut, it spawns a window and focuses it; if it's already in focus, it hides it. A user could choose to have several normal windows as well as one global "agent" window. All the other windows would show up as normal in the window switcher and dock. This config doesn't impact any of that - it only impacts the behavior of the one window spawned with the config, and users can choose to use it however they like.

And no, it doesn't show up in the bottom bar.

If it's a feature of the operating system and the user is explicitly choosing to use it, is it still sketchy?

2024-09-12 03:05 UTC, chrisduerr commented
> If it's a feature of the operating system and the user is explicitly choosing to use it, is it still sketchy?

It does not seem like this is the intended usecase of this feature at all though.

2024-09-12 03:11 UTC, purajit commented
> It does not seem like this is the intended usecase of this feature at all though.

How so? There may be certain applications that are more commonly used in this way, like application launchers, but a user could choose to run any window this way, no? It seems well within a standard workflow that a user might have applications bound to keys like this. It's how Guake and Yakuake function as well, so it's not unusual for terminals either.

2024-09-12 03:29 UTC, chrisduerr commented
> a user could choose to run any window this way, no?

If this was Apple's goals, then this would just be a feature for all applications out of the box.

2024-09-12 03:36 UTC, purajit commented
> > a user could choose to run any window this way, no?
> 
> If this was Apple's goals, then this would just be a feature for all applications out of the box.

It is (in two different ways - setting `LSUIElement` or `ActivationPolicy` (the latter overrides the former, which is why `LSUIElement` doesn't work for Alacritty), but Apple can't control how individual applications dynamically create their windows. But as far as Apple is concerned, this is actually a feature for all applications. But I get that you have a strong stance against this.

2024-09-13 17:27 UTC, chrisduerr commented
> Apple can't control how individual applications dynamically create their windows.

Considering it provides the APIs to do so, it can and it does.

> I get that you have a strong stance against this.

I don't mind it that much, I just don't understand its purpose or why anyone would use it. And upstream is obviously not the right place for stuff only one or two users use.

I don't use macOS so I can't speak of how reasonable this feature is, but unless there's more interest in this I'd rather hold off on this. There have been requests for a sort of daemon mode on all platforms, but so far no good arguments for its existence were made.

2024-09-13 17:27 UTC, closed without merging

2024-09-13 18:24 UTC, purajit commented
Just to give some context to wrap up

> And upstream is obviously not the right place for stuff only one or two users use.

This is of course your software, and I understand adding more things means more maintenance, especially when there's OS-specific settings involved, but given the number of asks here, I think this is actually pretty popular. "Quake-style console" gives a pretty huge number of results.

> I don't use macOS so I can't speak of how reasonable this feature is

I've been using Linuxes since I was ~10 and only had a Mac more recently. It's common there too, and felt reasonable. I used Guake as a kid and got used to the idea.

> but so far no good arguments for its existence were made.

Let's say I have my browser, chat, text editor (I tend to simultaneously use emacs both in terminal and as gui, depending on what seems to fit better in the moment). I have Alacritty able to be summoned on any desktop and any screen (I already have this) with a keypress. While I'm working between my editor and my browser while looking something up, I summon my terminal, spend some time in it, and go back to my editor. I want to continue working between my editor and browser. 

Same applies when you're working between your chat and browser window while answering a question, talking to someone while learning something; you summon the terminal to run some things and test things out, then you want to continue working between your chat and your browser.

Obviously, I can Alt-Tab twice to skip over Alacritty, but this happens so much and so frequently that not having Alacritty be first in Alt-Tab would make a huge difference, since it's common muscle memory to do it once to go back to where you expect. I don't think anyone particularly cares whether it's in the Dock or not - it's just the window switcher.

2024-09-13 20:48 UTC, purajit commented
> At least my understanding of this request is not the "singleton" approach of the terminal window, but the drop-down nature. I don't think your patch does anything to address this (not that it should)?

Yes, this patch only addresses the relationship with the window manager. Both the "dropdown" and "singleton" aspects are things left to the user and how they're automating things and binding their keys. The window manager part is just the last piece of the full UX, and something people who want the first two features tend to expect. It's definitely not the most important part - it's definitely not something that would stop me from using Alacritty.

> I can't say I know any Linux application that behaves like this which is a GUI application.

Guake, Yakuake (which is based on Konsole), Tilda, and of what I know, xfce4-terminal (haven't used) have configurations that allow it to behave like this. GNOME terminal has an [extension](https://github.com/ddterm/gnome-shell-extension-ddterm?tab=readme-ov-file) for it. I don't know how it's implemented at the window manager level, but the final behavior is the same - an application that can be excluded from the window switcher. It's definitely not a common thing outside of terminal emulators.

> At that point I'd just question the UX of that window manager. There's nothing that's unique about Alacritty here.

I guess that's true. Your point about "The whole point of the window switcher is to show your windows, is it not?" is definitely valid. I do appreciate your rigor and consistency in the philosophy of this whole thing, it's part of what's kept Alacritty great. However, I think basically any window manager right now has this capability in some shape of form, and it's something people have found a use for. I fully understanding closing this, and thanks a lot for engaging to this depth.

2024-09-13 21:14 UTC, chrisduerr commented
> However, I think basically any window manager right now has this capability in some shape of form, and it's something people have found a use for.

I think this makes a big difference though. In the past I've used things like i3's scratchpad for password managers, before I switched to TUIs. That definitely makes sense to me but it doesn't change application behavior **at all**. This seems to require modifying the application behavior to change the way it is managed by the WM, which doesn't surprise me for Apple but seems extremely backwards to me.

Ultimately I'd say if there's a significant amount of people actually interested in this, I'm willing to reconsider. But I've never even heard of this before so for now I'd just recommend running a fork if you're interested. If other people try this patch and think it's worthwhile upstreaming, feel free to let me know.

2024-09-16 17:29 UTC, purajit commented
By the way, some updates:
* The reason setting `LSUIElement` wasn't working is that by default `winit` doesn't honor the package manifest (even if the application developer sets it), since they force an `activation_policy` of `Regular`, which overrides the package manifest. They have a `with_activation_policy` to allow app devs to override that. (This is related to what I linked in the PR)
* Now that https://github.com/rust-windowing/winit/issues/261 is closed, `winit` will honor the package manifest unless the application itself explicitly enforces an `activation_policy`. If the manifest sets `LSUIElement = true`, it will be launched as an `Accessory` (what I want), otherwise as a `Regular` window (current behavior). This basically allows me to get what I need without any Alacritty changes, once the dependency is bumped.
* This doesn't _completely_ invalidate this PR, since people would need to edit the manifest on every Alacritty upgrade, and it would be nice to have it as a config. However, if you believe that this is something only certain people might want to do, and if they want to do it, they should take on that slight inconvenience, that's fine by me. As an FYI here are two other issues where people have brought it up: https://github.com/alacritty/alacritty/issues/5446 https://github.com/alacritty/alacritty/issues/6779, and I do believe that if exposed, more people would use it.

2024-11-29 10:20 UTC, ilyastuit commented
Hi there
This feature would be very useful for a users who prefer behavior similar to Guake or iTerm. It seems that the current macOS API doesn't work correctly. Are there any chances of reconsidering or exploring alternative solutions to implement this?

2024-12-02 08:09 UTC, purajit commented
@ilyastuit winit hasn't cut a release since my PR above - you'll have to make your own build of Alacritty with a manual dependency change, and after that, setting `LSUIElement` will work.