Add IME support to inline search
alacritty/alacritty pull request #8234
Opened 2024-10-11 23:19 UTC by chrisduerr

This changes the behavior of inline search from only accepting direct key inputs, to also accepting IME and paste. The additional characters are still being discarded, matching the existing behavior.

This also fixes an issue where inline search wouldn't work for characters requiring modifiers, since the modifier press was interpreted as the search target instead.

Closes #8208.

2024-10-12 00:28 UTC, nixpulvis commented
Ah, this is great, thanks.

2024-10-12 00:29 UTC, nixpulvis approved these changes

2024-10-14 17:01 UTC, kchibisov commented on alacritty/src/event.rs
> +        self.inline_search_state.character = Some(c);
I'd probably reset it to `None` at the `start_inline_search`.

2024-10-14 17:15 UTC, kchibisov requested changes
You need a CHANGELOG entry.

And for IME to work you need the following patch:

```diff
diff --git a/alacritty/src/display/mod.rs b/alacritty/src/display/mod.rs
index 51553288..1e2da20f 100644
--- a/alacritty/src/display/mod.rs
+++ b/alacritty/src/display/mod.rs
@@ -882,8 +882,12 @@ impl Display {
             },
             None => {
                 let num_lines = self.size_info.screen_lines();
-                term::point_to_viewport(display_offset, cursor_point)
-                    .filter(|point| point.line < num_lines)
+                if vi_cursor_viewport_point.is_some() {
+                    vi_cursor_viewport_point
+                } else {
+                    term::point_to_viewport(display_offset, cursor_point)
+                        .filter(|point| point.line < num_lines)
+                }
             },
         };

diff --git a/alacritty/src/event.rs b/alacritty/src/event.rs
index 1ca5711f..f4167a6a 100644
--- a/alacritty/src/event.rs
+++ b/alacritty/src/event.rs
@@ -1317,6 +1317,7 @@ impl<'a, N: Notify + 'a, T: EventListener> input::ActionContext<T> for ActionCon

         self.inline_search_state.char_pending = false;
         self.inline_search_state.character = Some(c);
+        self.window().set_ime_allowed(false);

         // Immediately move to the captured character.
         self.inline_search_next();
diff --git a/alacritty/src/input/keyboard.rs b/alacritty/src/input/keyboard.rs
index 9668cc3c..14755594 100644
--- a/alacritty/src/input/keyboard.rs
+++ b/alacritty/src/input/keyboard.rs
@@ -28,6 +28,9 @@ impl<T: EventListener, A: ActionContext<T>> Processor<T, A> {
         let mods = self.ctx.modifiers().state();

         if key.state == ElementState::Released {
+            if self.ctx.inline_search_state().char_pending {
+                self.ctx.window().set_ime_allowed(true);
+            }
             self.key_release(key, mode, mods);
             return;
         }

```

The key point here is that you have to enable it on `Release` for the key that started the search (f/F) and then disable on exit. Also, you have to use the `vi_cursor_viewport_point` in such case to hint the IME position, otherwise it'll be somewhere where the original cursor was.

2024-10-15 08:42 UTC, kchibisov approved these changes

2024-10-15 14:06 UTC, merged