On macOS, explicitly focus the new window in case Alacritty isn't the active app, otherwise it won't get focus automatically
alacritty/alacritty pull request #8288
Opened 2024-11-02 00:03 UTC by chipschipschips

On macOS, explicitly focus the new window in case Alacritty isn't the active app, otherwise it won't get focus automatically.

This is continuing from [PR !8283](https://github.com/alacritty/alacritty/pull/8283) for issue #8283

On macOS, when [`window.set_visible(true)`](https://github.com/alacritty/alacritty/blob/d552c6b251d199b4913754dd25fca330f87651fd/alacritty/src/display/mod.rs#L485) is called, winit's [AppKit delegate](https://github.com/rust-windowing/winit/blob/d3207a8d76c7b6a6283dee36c19c1dac4e378fa7/src/platform_impl/apple/appkit/window_delegate.rs#L921) calls [`NSWindow.makeKeyAndOrderFront`](https://developer.apple.com/documentation/appkit/nswindow/1419208-makekeyandorderfront) which moves the window to the front of the application's screen list and makes it the key window for that application. If the application itself is already active, then great, the window has focus. If the application isn't active, then the window doesn't get focus.

This change explicitly focuses the window.

I kept `focus_window` in `alacritty::display::window::Window` and called it from `alacritty::display::Display::new`; cramming the call to `self.window.focus_window() in `set_visible` didn't seem appropriate. Setting [`.with_active(true)` on `window_attributes`](https://github.com/alacritty/alacritty/blob/d552c6b251d199b4913754dd25fca330f87651fd/alacritty/src/display/window.rs#L166) has no effect.

`make app` and `cargo test` succeed on macOS 15.1. Manual tested and the change seems to work as expected.  
`make binary`  and `cargo test` succeed on Ubuntu 24.04. Manual tested and the app still works.

2024-11-02 02:15 UTC, chrisduerr requested changes
Requires a changelog entry in the `changed` section.

2024-11-02 02:15 UTC, chrisduerr commented on alacritty/src/display/mod.rs
> +        // otherwise it won't get focus automatically.
```suggestion
        // Automatically focus new windows, even if no Alacritty windows are currently focused.
```

2024-11-02 03:13 UTC, chipschipschips commented on alacritty/src/display/mod.rs
> +        // otherwise it won't get focus automatically.
Much more succinct - thanks.

2024-11-02 06:06 UTC, chrisduerr requested changes
Bit bikesheddy, but after this it should be good to go.

2024-11-02 06:06 UTC, chrisduerr commented on alacritty/src/display/mod.rs
> +        // Automatically focus new windows, even if no Alacritty windows are currently focused.
```suggestion
        // Always focus new windows, even if no Alacritty window is currently focused.
```

I know I suggested this myself, but that's just garbage English.

2024-11-02 06:06 UTC, chrisduerr commented on CHANGELOG.md
> +- Automatically focus new windows on macOS, even if no Alacritty windows are currently focused
I think this is a bit long for a changelog message, I'd like to keep it under 80 columns where possible.

```suggestion
- Always focus new windows on macOS
```

I don't think pointing out the delta to the previous behavior is necessary. If people thought it already behaved like this, they can just ignore this changelog.

2024-11-02 19:22 UTC, chrisduerr approved these changes

2024-11-02 19:23 UTC, merged

2024-12-30 09:26 UTC, glensc commented
oh damn, how I hate when apps steal focus. I might be typing something!

2024-12-30 10:35 UTC, kchibisov commented
You probably don't understand what it does then.