Alacritty version 0.14.0-rc1
alacritty/alacritty pull request #8356
Opened 2024-12-14 01:10 UTC by chrisduerr

---

Just added all the minor patches that have built up since the last release, should be a pretty uncontroversial one I think. Features held back for 0.15.0, alacritty_terminal is the only changed dependency crate and it's non-breaking.

2024-12-16 16:53 UTC, kchibisov requested changes
I'd wait for winit to release 0.30.6.

https://github.com/rust-windowing/winit/pull/4042

2024-12-17 00:28 UTC, chrisduerr commented
Will also pull in the non-breaking dep bump from master.

2024-12-22 22:30 UTC, kchibisov requested changes

2024-12-22 22:30 UTC, kchibisov commented on alacritty_terminal/CHANGELOG.md
> +- Semantic escape search across wide characters
it doesn't have section.

2024-12-22 22:30 UTC, kchibisov commented on CHANGELOG.md
> +- Crash when pressing certain modifier keys on macOS 15+
wrong rebase.

2024-12-22 22:30 UTC, kchibisov commented on CHANGELOG.md
> +- Always emit `1` for the first parameter when having modifiers in kitty keyboard protocol
wrong rebase.

2024-12-22 23:20 UTC, kchibisov approved these changes

2024-12-22 23:22 UTC, merged